### ISSUE TITLE
Artifactory Backups

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#105]
## Problem statement:
We currently do not have any disaster recovery options for our artifactory service.

## Definition of done

- [x] Metadata backups (Postgresql backups) to an enterprise backup location
- [x] Artifact backups? (less required once artifacts are stored in the object store)
- [ ] Other application backups required?

**Comment by caggles** [comment]
We have backups running on both lab and prod now - artifactory has full import/export backup functionality. 

Next up, I'm going to break lab on purpose and see how the recovery works. If it works nice, I believe the future plan should be to leave it as-is for now and get to work on setting up the object store. Then, once the object store is working, we can set it up so that the backups go to their own bucket in the object store, which should be an acceptable enterprise backup location. 

I'll also look into whether or not we can exclude objects from the backup without also excluding the metadata.

**Comment by caggles** [comment]
Recovering using the built-in import/export works when postgres tables are emptied (or at least some of them), but deleting entire tables prevents the import from recovering the same instance. I'm in the process of rebuilding the lab environment from scratch to see what happens when I import after that. It looks like there's an issue with Aporeto at the moment - progress is blocked until that's fixed.

**Comment by caggles** [comment]
There are underlying issues on the lab cluster that are causing significant delays and issues with the progress of this task.
