### ISSUE TITLE
Github Backups - Requirements Gathering

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/developer-experience#1141]
**Describe the issue**
We currently don't have repository or organization wide github backups.

**Additional context**
Alternative Paid Solution:  https://www.backhub.co/

**Definition of done**
- Define what we need to backup:
  - Which Organizations?
  - Which Repositories? Do we only backup our teams repositories?
  - Issues? (Restores will not retain original author and comment authors)
  - Wikis?
  - Branches? Just master/main , all?
  - Releases?
  - Member Access? (Is this possible with / without BackHub?)
- BackHub or Custom Solution?
- AWS S3 or BCGov Object Storage (S3) for storage
- Frequency of backups?

**Comment by IanKWatts** [comment]
One important detail of the BackHub service is that the backups are stored in AWS in Germany, in the eu-central-1 region.  The backups are encrypted in transit and in storage.  @NickCorcoran would that be a deal-breaker?

Otherwise, BackHub provides a convenient service:
- 150 USD per month for up to 300 repos
- Can automatically include new repos added to the org
- Includes almost all resources, including issues and pull requests
- Restoring a repo would be simple and easy

It uses the GitHub APIs that we would also use if deploying a home-grown solution, so with a little work we could get much of what BackHub offers, though there would be costs associated with the home-grown solution, too.

GitHub Secrets are not included in the backups.  We should work on a strategy for storing and restoring secrets.

**Comment by juhewitt** [comment]
Two requirements from me.  We're looking primarily into repository backups for GitOps services, or other repositories that would lead to catastrophe for PaaS.  Hence, cost to start would be very small potentially.  Secondly, I'd like to see if we can add S3 in CAD versus the Germany S3 region.  That might be contact sales etc...

**Comment by IanKWatts** [comment]
@juhewitt Would this be an all-new AWS account for us?  Is there someone I should contact to see about getting that going?

**Comment by NickCorcoran** [comment]
@IanKWatts I would think our Cloud Pathfinder team would be the best for that detail.  Julian Subda would likely be a good starting place.

**Comment by mitovskaol** [comment]
@IanKWatts Please have a look at the S3 Object Storage service offered by OCIO Enterprise Service Branch ( @caggles can give you our key to the S3 bucket).

Also, including a note about the security aspect of using the Github Actions that we hope more teams will start using instead of Jenkins

```
Nick does not have any specific concerns about GitHub Actions.  There was a particular vulnerability that has been fixed.  Otherwise, GitHub publishes recommendations on security for Actions.  As part of our guidance for teams on the adoption of GitHub Actions, I will include a summary of these security best practices and a link to the GitHub doc.

**Comment by IanKWatts** [comment]
@caggles has confirmed that we can create a new bucket for this.  I suggest calling it 'github-backups'.

@j-pye @juhewitt  From our previous discussion, I got the impression that we would back up all repos in the 'bcgov-c' and 'BCDevOps' orgs.  Does that sound reasonable?

As for what to back up, I think we should get everything that we can, though we will probably want to only do the full backup on a weekly basis, because this would be a time-consuming process.  We could do a daily backup that is much leaner and faster.

@j-pye  I like a good home-grown solution as much as anyone, but check out this project.  It is actively supported, has good features, and has quite a few contributors:
https://pypi.org/project/github-backup/
https://github.com/josegonzalez/python-github-backup

**Comment by IanKWatts** [comment]
With the exception of the actual repository list for backing up, the requirements gathering is complete and we are just about ready for implementation.  We have a meeting scheduled Friday morning, May 21 to discuss repos needing backup, at least for starters.

- A utility server image has been prepared for running backup scripts
- An OpenShift CronJob in the gitops-tools project will run the utility server container and backup script
- A ConfigMap in that project will be used to manage the repo list for backups
- Backups will be stored in an S3 bucket called 'github-backup' in the OCIO S3 service, as well as in the PV used by the utility server
- The initial backup script uses a program called 'github-backup', which simplifies the fetching of all manner of non-code resources from GitHub, such as issues, milestones, pull requests, etc.

**Comment by mitovskaol** [comment]
@IanKWatts  What would be the scenario for when we need to restore our GitHub repos from the backups?

**Comment by juhewitt** [comment]
@mitovskaol  they magically get deleted... lets just pretend... they get corrupted, deleted, disappear... and we can't get them back quickly enough, or ever... ;)

**Comment by IanKWatts** [comment]
@mitovskaol @juhewitt The recovery method will depend on:
- what happened to the original repo
- whether we need to restore just files or everything, like issues, pull requests, etc.

If it's just the files, that would be fairly quick and easy.

If we are restoring other resources, it will take a lot longer, because of the number of API calls that would have to be made.  There are rate limits on API calls and some of them would result in email notifications being sent.  Not a big deal for a repo or two, but would be if we had to restore many repos.  Other resources that could be backed up (we'll talk about this on Friday) include:
- issues
- pull requests
- milestones
- labels
- hooks
- starred repositories
- watched repositories
- followers

I think we should document how these scenarios would be handled, but don't expect that we need to try to prepare a fully automated recovery tool.  The BackHub service claims to have a one click restoration process, though it uses the same GitHub APIs that we would use for recovery.

**Comment by IanKWatts** [comment]
The requirements for GitHub backups have been established.  These could be changed, of course, as needed, but this is what we have for starters.

_Which Organizations?
Which Repositories? Do we only backup our teams repositories?_
We have selected a relatively small number of repositories to back up.  For now, the list includes:
- bcgov/platform-services-registry
- bcgov-c/platform-gitops-gen
- bcgov-c/platform-gitops
- bcgov-c/platform-gitops-kamloops-silver
- bcgov-c/platform-gitops-kamloops-klab
- bcgov-c/platform-gitops-calgary-clab
- BCDevOps/platform-services
- BCDevOps/developer-experience

_Issues? (Restores will not retain original author and comment authors)
Wikis?
Branches? Just master/main , all?
Releases?
Member Access? (Is this possible with / without BackHub?)_

We have two modes of backup:
- just the files, including all branches and the basic Git info
- everything, including issues, pull requests, milestones, etc.

The repos from the list above where we are backing up everything are:
- bcgov-c/platform-gitops-gen
- bcgov-c/platform-gitops
- BCDevOps/developer-experience

Note that the developer-experience repo is where all of these ZenHub issues are managed.

_BackHub or Custom Solution?_
The BackHub service stores all backups in Germany, and we'd rather keep them in Canada and use the BC government's S3 service, so this is a custom solution.  A shell script in the 'utility-server' build in the gitops-tools namespace does the backups by way of OpenShift cron jobs.

_AWS S3 or BCGov Object Storage (S3) for storage_
BCGov S3

_Frequency of backups?_
Daily.  We will revisit the setup soon to evaluate disk space usage, priority of backups, and effectiveness of backups.
There is also a limit on the number of GitHub API calls that can be made (5,000 per hour when authenticated).  This is an issue when doing a full backup of the 'developer-experience' repo, for example, because there are two API calls for each issue and there are over 1,000 issues, as well as all the other API calls made for other repos.  Some repo backups will probably be moved to separate cron jobs so they can be spread out to stay under the limit.
