### ISSUE TITLE
CCM Push for Argo Upgrades in SILVER and GOLD clusters

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1252]
**Describe the issue**
Due to some requirements for key system services like Argo needing upgrades, we need to increment the CCM release version in both SILVER and GOLD clusters. DXCAS will need to coordinate/schedule appropriate RFCs for this.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- [x] Confirm with Justin Pye the new release has been generated that properly encapsulates all required changes.
- [x] Schedule RFCs for work in SILVER and GOLD, confirm approval by Olena. 
- [x] Implement in SILVER (CHG0027298 scheduled for June 23rd)
- [x] Implement in GOLD if no issues with SILVER (CHG0027406 scheduled for June 30th)

**Comment by wmhutchison** [comment]
This will be moved to Sprint 29 since we're not in a position yet to push this forward in SILVER/GOLD.

**Comment by j-pye** [comment]
Sounds good: 

@wmhutchison 
ArgoCD Upgrade PR: https://github.com/bcgov-c/platform-gitops-gen/pull/175
Outlines upgrade process and intent

ArgoCD Upgrade Misc Fixes PR: https://github.com/bcgov-c/platform-gitops-gen/pull/176

Currently, the new version is live in KLAB. The grafana operator is flapping a little on one resource. I'm going to try to connect with @tmorik today to get that sorted before tagging a release. It's not a huge issue but probably worth fixing before tagging since we don't do releases very often.

**Comment by wmhutchison** [comment]
In progress, looking good. Will confirm later and close off checkbox.

**Comment by wmhutchison** [comment]
Justin Pye has setup the required Github repo for GOLDDR. Tim Baker will execute an RFC for configuring oauth for GOLDDR the evening of June 29th.

Barring any new issues/etc, we estimate completion of this task by end of day June 30th.

**Comment by wmhutchison** [comment]
Upgrade in GOLD complete.
