### ISSUE TITLE
Vault Prod GSLB Issue - SPIKE

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/developer-experience#1391]
There appears to be a problem with the GSLB for Vault Prod. The GSLB for Vault Lab is working as expected.

**Vault Prod:**
Entry Point: https://vault.developer.gov.bc.ca/
Active Site:  https://one.vault.developer.gov.bc.ca/
- Status: Deployed
- ClusterName: Silver

Failover Site:  https://two.vault.developer.gov.bc.ca/
- Status: Not Deployed
- ClusterName: ARO Platform-Services (Decommissioned)

**Vault Lab:** 
Entry Point: https://vault-lab.developer.gov.bc.ca/
Active Site: https://one.vault-lab.developer.gov.bc.ca/
- Status: Deployed
- ClusterName: KLAB

Failover Site: https://two.vault-lab.developer.gov.bc.ca/
- Status: Not Deployed
- ClusterName: CLAB

Health Check Endpoint for one.* and two.*: /v1/sys/health?standbyok=true

**What’s happening:**
The Vault Prod entry point is rotating between the active site and the failover site constantly even though nothing is running at the failover site. The health check for the active site is passing as expected and the health check on the failover site is always failing as expected right now since the failover site is not set up. Due to the constantly changing entry point the vault web ui either doesn't load or loads and then fails when trying to perform any additional actions on the page.  This also affects the vault cli tool since it goes through the same entrypoint

Confirmed with curl, ping, and pod logs.

**What should be happening:**
The Vault Prod entry point should be pointing at the vault active site without changing because there's nothing deployed at the failover site. Navigating to the Vault Prod entry point should display the vault web ui consistently. 

**Thoughts:**
- Possibly GSLB Configuration differs from LAB
- Could just be that the invalid IP for the Prod Failover site is causing the issue

**Additional Information**
- An issue has been opened by DXC with the F5 / GSLB team

**Comment by wmhutchison** [comment]
Internal ticket created (RITM0097438), will follow through more after my lunch break.

**Comment by wmhutchison** [comment]
Received an initial response from Network team who stated at the time they checked all members were down for the PROD GLSB.

Am pursuing some fixes with the following.
- update two.developer.gov.bc.ca with correct IP - DONE
- create new ticket requesting update to GLSB for correct IP - DONE (RITM0097652 created for expedited implementation).

**Comment by wmhutchison** [comment]
Meeting held today with Network and F5 stakeholders.

**First item regarding PROD Vault**
Health check is setup correctly in terms of the query, but is looking for an incorrect response code. Is supposed to be looking for HTML code 200, but was setup to look for 503 instead. 

**Second item regarding PROD Vault**
There is only a single health check that is currently applied to all member IPs. This is incorrect, since said health check is for `one.vauilt.devops.gov.bc.ca`. The health check for `one` needs to have the current host in place, and the health check for `two` needs to have its check use the Host `two.vault.devops.gov.bc.ca`. Not an issue right now since `two` is not working, but when this goes into production, this being setup correct will matter.

**Third item regarding PROD Vault**
The default behavior for F5 GLSB when no member IPs pass the health check is to return the IPs for all members, which is what we're seeing right now. This can be changed to `None` do not return any DNS results when all members are healthy, or a single IP address as a fail-back can be configured (no DNS entries allowed).

**Comment by wmhutchison** [comment]
With current workloads/etc, F5 stakeholders expect to have Vault PROD fixed with respect to the health checks by next Monday. We can then take aside the scenario of how we want Vault services to react when said scenario of no available members is ever achieved (should be almost impossible due to current architecture)

**Comment by j-pye** [comment]
Working now. This appears to be resolved. Closing.
