### ISSUE TITLE
We Need Control Over cloud.gov.bc.ca

### ISSUE THREAD

**Issue by juhewitt** [BCDevOps/developer-experience#1431]
**Describe the issue**
We need to get control over the domain name, cloud.gov.bc.ca, as this could be used for multiple web properties moving forwards.

**Additional context**
It's best practise in SEO, as well in information architecture, to also align with our upcoming content strategy, to claim ownership of a domain name that will directly correlated to our primary personas.  We have developer.gov.bc.ca, we need cloud.gov.bc.ca.

**Definition of done**
Have ownership for the usage of cloud.gov.bc.ca

**Comment by juhewitt** [comment]
Submitted request to DNS management to transition.  @mitovskaol I may need help uncovering our ADMIN group should DNS require it, so if we can connect with the Platform Admins in case I don't know the answer.

**Comment by juhewitt** [comment]
@sheaphillips  this the ticket as per that email and it's purpose.

**Comment by juhewitt** [comment]
@sheaphillips has gone into NNR, and identified that we own this domain and subdomains, yeah!!!  and secondly, that we need to update owners, add more cloud pathfinder representation, and updated some records accordingly.

@marthaedwards good news!

**Comment by mitovskaol** [comment]
@sheaphillips Can you please set myself, @juhewitt , Cailey, Shelly and Patrick are admins of this domain in NNR.

**Comment by sheaphillips** [comment]
Luke, Cailey, Shelly and Patrick are already Admins.   I have lesser
"Update" level access.

I don't believe access can be edited through NNR.  My understanding is that
access within NNR is managed via something called "Admin Groups", which may
or may not be the same thing as Active Directory groups. In any case, Luke
knows who to contact/how to add/change in order to get
yourself and @juhewitt in there.

Note that CPF team will need to retain access, and per @juhewitt should
add @ActionAnalytics.

**Comment by mitovskaol** [comment]
@lukegonis Can you pretty please confirm that :  myself, @juhewitt , Cailey, Shelly,  Patrick and @ActionAnalytics are included in the " Admin Group" for `cloud.gov.bc.ca` domain in Remedy/NNR. Thank you!
