### ISSUE TITLE
2021Q3 Maintenance - Develop Proof of Concept OCP 4.7 Upgrade on a LAB cluster

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1483]
**Describe the issue**
While a change freeze on all OCP4 PROD clusters exists for Q3 (due to Wildfire concerns), we can still proceed with taking one of the LAB clusters, work out all of the issues that might come up with upgrading to OCP 4.7, and polish things up so that when Q4 arrives and we're no longer frozen on PROD clusters, we can push forward quickly with OCP 4.7 upgrades across the board.

**Additional context**
<https://docs.openshift.com/container-platform/4.7/release_notes/ocp-4-7-release-notes.html>

A driver for getting this done sooner rather than later relates to GOLD cluster's Kubernetes CA cert, which based on expiry and calculations by Red Hat, will kick off its automated rotation around the date of October 25th 2021. Ideally we'd like to have 4.7 worked out in LAB and both SILVER and GOLD upgraded prior to that if possible, or if not, we encapsulate the automation with a suitable RFC.

**Definition of done**
- [ ] Work out initial changes required to playbooks/etc for the upgrade (new branch)
- [ ] Successfully test out an upgrade to OCP 4.7 in a LAB cluster.
- [ ] Confirm by draining/deleting an APP node that (re)building nodes in OCP 4.7 also works.

**Comment by StevenBarre** [comment]
- Should also upgrade F5 CIS to latest, 2.5.0 required for 4.7
- Should also upgrade Trident to latest, but current version will work on 4.7
- Descheduler is generally available. Look into enabling this? Might improve node balancing.
- New API Performance monitoring dashboard - ooooo need to check this out
- OpenShift Pipelines goes GA - will need some testing and docs from Jason

Known Issues:
- If you are running a cluster on VMware that uses x86_64 architecture and has the platform: none field set in the install-config.yaml file, a fresh installation on OpenShift Container Platform cluster version 4.7 or an upgrade from cluster version 4.6 to version 4.7 might fail. This failure happens when a cluster uses virtual machines (VMs) that are configured with virtual hardware version 14 or greater. As a workaround, you can configure VMs to use virtual hardware version 13.
- If you are running cluster monitoring with an attached PVC for Prometheus, you might experience OOM kills during upgrade to OpenShift Container Platform 4.7. When persistent storage is in use for Prometheus, Prometheus memory usage doubles during cluster upgrade and for several hours after upgrade is complete. To avoid the OOM kill issue, allow worker nodes with double the size of memory that was available prior to the upgrade. (BZ#1925061)
- Starting and stopping pods rapidly can result in pods getting stuck in the Terminating state.

**Comment by StevenBarre** [comment]
Created #1544 as an Epic to track all 4.7 upgrade work and steps. Closing this ticket.
