### ISSUE TITLE
OCP4.7 Main Epic

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1544]
**Describe the epic**
Top level epic to track all OCP 4.7 upgrade work separate of quarters or sprints. Sub tasks may end up in multiple epics for better tracking and grouping.

**Additional context**
https://docs.openshift.com/container-platform/4.7/release_notes/ocp-4-7-release-notes.html

**Definition of done**
All clusters upgraded to OCP 4.7 and all post-upgrade tasks completed.

**Comment by StevenBarre** [comment]
@juhewitt @mitovskaol @sbathgate tentative dates for upgrades:

- Oct 3rd CHG0029872 MCS SILVER - 2021 Q4 Patching - Registry Hard Prune
- Oct 4th – 15th CHG0029876 MCS SILVER - 2021 Q4 Patching - Upgrade to OCP 4.7
- Oct 17th CHG0029877 MCS GOLD - 2021 Q4 Patching - Registry Hard Prune
- Oct 18th – 22nd CHG0029878 MCS GOLD - 2021 Q4 Patching - Upgrade to OCP 4.7
- Oct 24th CHG0029880 MCS GOLD DR - 2021 Q4 Patching - Registry Hard Prune
- Oct 25th – 29th CHG0029881 MCS GOLD DR - 2021 Q4 Patching - Upgrade to OCP 4.7

These dates are assuming the Wildfire change freeze ends before then. Also we are waiting on a security fix to be released by Red Hat and tested in KLAB.

We don't expect the Silver upgrade to take a full 2 weeks, but want to ensure we have enough time given the number of nodes in the cluster and that some of them will need a couple reboots to pick up OS and Firmware changes. Also the second week has a stat holiday for Thanksgiving and is a short week. By the 15th we should know if Silver is stable and safe to proceed onto GOLD or not. If you'd like more soak time for the upgrade before proceeding to GOLD, or more time between GOLD and GOLDDR,  please let us know.

Given that these will take about a month to do, December has a holiday change freeze, and several people on the team have vacations, we don't plan to squeeze in a 4.8 upgrade in Q4. We'll get the ball rolling around the end of Nov to do the testing in the LAB and aim to start PROD upgrade to 4.8 in January 2022.

**Comment by mitovskaol** [comment]
@juhewitt @StevenBarre What do you think about deciding on a rule of thumb for the duration of the "soak" period between Silver and Gold upgrades - we can wait a week until after the last Silver node is finished upgrading or we can wait a week after at lest 50% of all Silver nodes are upgraded?

**Comment by StevenBarre** [comment]
@mitovskaol looks like at the top of https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Upgrade.md we had previously settled on a week between. I can push GOLD to Oct 25th – 29th and GOLDDR to Nov 8th - 12th.

**Comment by StevenBarre** [comment]
Updated dates, and added an extra change to cover HPE firmware in Silver and get the SSDs from the old gluster nodes added into the silver nodes still on HDD drives.

- Oct 3rd CHG0029872 MCS SILVER - 2021 Q4 Patching - Registry Hard Prune
- Oct 4th – 15th CHG0029876 MCS SILVER - 2021 Q4 Patching - Upgrade to OCP 4.7
- Oct 18th - 22nd CHG0029890 MCS SILVER - 2021 Q4 Firmware Patching and Upgrade nodes to SSDs
- Oct 24th CHG0029877 MCS GOLD - 2021 Q4 Patching - Registry Hard Prune
- Oct 25th – 29th CHG0029878 MCS GOLD - 2021 Q4 Patching - Upgrade to OCP 4.7
- Nov 7th CHG0029880 MCS GOLD DR - 2021 Q4 Patching - Registry Hard Prune
- Nov 8th – 12th CHG0029881 MCS GOLD DR - 2021 Q4 Patching - Upgrade to OCP 4.7

**Comment by StevenBarre** [comment]
@caggles to provide steps for putting EDB clusters into maintenance mode to remove their non-disreputable PDBs.

**Comment by mitovskaol** [comment]
Notes from running the OCP 4.7 Upgrade in Silver
- Pulling images from local project failing https://bugzilla.redhat.com/show_bug.cgi?id=2000216

- Audit log spam https://access.redhat.com/solutions/6387661

- pods limits and requests are not displayed anymore in the web console

- Struggles with HDD based nodes taking a long time (30+ min) after reboot to become stable. Pods taking a very long time to start on node. Possible that Aqua is also impacting this doing image inspections on pod starts?

- HPA log spam due to missing or incorrect apiVersion in spec

- Trident pull image from docker, but doesn’t use docker.io prefix, so pull secret isnt used. Can use ansible to pre-pull image on all nodes.

Deploy pods stuck in terminating. Bug fixed in 4.7, but causing node drains to fail until manual intervention https://access.redhat.com/solutions/6009101
ipfamilies log spam from kube controller

- EDB pod failed to start in Karim’s test ns, causing the PDB to prevent node drain

Overall though, much less EDB issues than expected. Seems the Primary PDB issues we were expecting never materialized?
