### ISSUE TITLE
Best Practices for Jenkins resource allocation

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1706]
As part of the resource utilization optimization campaign on the Platform, the Platform Services Team noticed that some of the biggest mismatch between CPU Request and the actual CPU usage comes from the tools namespaces in Openshift that run Jenkins pipelines. We are looking for help from Arctiq to come up with the best practices/recommendations that we can take to teams to help them configure Jenkins pods more efficiently.

**Comment by Nicole-Huard** [comment]
@Markieta @gregnrobinson please see work previously completed by Jeff Kelly: https://developer.gov.bc.ca/Resource-Tuning-Recommendations

**Comment by Nicole-Huard** [comment]
Review and update the old recommendations in this markdown and add more content as needed: https://github.com/BCDevOps/developer-experience/blob/master/docs/resource-tuning-recommendations.md
Create a PR with changes and tag Olena for review

**Comment by Nicole-Huard** [comment]
Update from Chris:
I've researched all options to mitigate over-allocation of cluster resources due to multiple Jenkins instances in a multi-tenant environment.
I've completed labbing of Jenkins instances with reduced resource requests, limits, and quotas.
I have started the documentation process to add onto Jeff's previous findings. I expect to have a PR to that doc by EOW.
I also have asked for some info from Justin in RC, but have not received a reply yet.

**Comment by Markieta** [comment]
@mitovskaol [PR](https://github.com/BCDevOps/developer-experience/pull/1977) ready for review.

Sorry for Fri eve `@mention`, this can certainly wait until Monday.

**Comment by mitovskaol** [comment]
@Markieta The images mentioned in the doc seem to be missing from the repo.

**Comment by Markieta** [comment]
Hey @mitovskaol, this is because the images are included in the PR and GitHub doesn't render the `.md` correctly until those files are merged in.

You can see a working rendering of it [here](https://github.com/Markieta/developer-experience/blob/jenkins-resource-allocation/docs/resource-tuning-recommendations.md).
