### ISSUE TITLE
OCP Login Page - Developer Access - 2 buttons for IDPs

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1794]
On the OCP login page, create 2 buttons under the Developer Login umbrella to include:
- [x] GitHub
- [x] IDIR (via Azure AD login)

**Comment by j-pye** [comment]
Additional Context: 
https://github.com/bcgov-c/platform-gitops-gen/blob/master/roles/ocp_oauth/templates/login.html.j2

If this is still a desired feature, the idea was to modify the template to include a button for github and a button for IDIR instead of the single `Developer Log In` button. Each of these buttons would have `idpHints` which would automatically make the proper selection on the keycloak page that currently pops up when logging in. This feature would remove the extra click at login and when copying the users OCP token.

**Comment by w8896699** [comment]
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/2464

After done servial tests as described in above ticket, and read through https://technospace.medium.com/csrf-in-idp-initiated-openid-connect-7a2873420e86. Gerald Nunn and I agree that this may not achieveable with openshift mechanism.
