### ISSUE TITLE
Issue with Sysdig - not getting system dashboards when adding my team in OpenShift

### ISSUE THREAD

**Issue by arcshiftsolutions** [BCDevOps/developer-experience#1871]
**Describe the issue**
I'm not getting the expected system dashboards when adding my team in OpenShift.

**Additional context**
![Clipboard - November 9, 2021 2_58 PM](https://user-images.githubusercontent.com/51424896/141021550-10c8d638-f938-4b4a-a98e-152dd3aa800d.png)

**Definition of done**
Hoping to get the system dashboards created when adding my team.

**Comment by ShellyXueHan** [comment]
### Update:

this happens when there are multiple admin users in the CR, where one of then is not activated yet. The operator will first create the sysdig team, then assign all the admins. Afterwards, it’ll fetch the admin users, grab the first one from list and use that as the owner of the dashboard. This will cause silent failure.

For now, please double check with your team to make sure they have all logged into sysdig and confirm the correctness of the email account! I'll update documents to reflect this as well!

**Comment by arcshiftsolutions** [comment]
Thanks so much @ShellyXueHan !
