### ISSUE TITLE
Artifactory App Baseline Monitoring / Alerts

### ISSUE THREAD

**Issue by sbathgate** [BCDevOps/developer-experience#1882]
**Describe the issue**
To ensure proper support and response to Platform Services applications issues, baseline monitoring and alerting is necessary within Sysdig. This includes the following:

Saturation Monitoring (alerts > 80%):
- [x] CPU Utilization
- [x] Memory Utilization
- [x] Storage Utilization

**Definition of done**
When the Platform Services application below have at least the Baseline Monitoring/Alerting Configurations setup.
- [ ] Artifactory

**Comment by ShellyXueHan** [comment]
### Update:

Let's postponed this ticket for now since we are having issues with both sysdig PVC metrics and events :P

**Comment by ShellyXueHan** [comment]
### Update:

dashboard setup here: https://app.sysdigcloud.com/#/dashboards/256940?last=3600&scope=kubernetes.cluster.name%20in%20%28%22silver%22%29%20and%20kubernetes.namespace.name%20in%20%28%22devops-artifactory%22%29


Currently blocked because PVC metrics are missing from sysdig (issue #). Will continue once that issue is fixed!

**Comment by ShellyXueHan** [comment]
dashboard created here: https://app.sysdigcloud.com/#/dashboards/256940?last=3600&scope=kubernetes.namespace.name%20%3D%20%22devops-artifactory%22%20and%20kubernetes.cluster.name%20%3D%20%22silver%22
