### ISSUE TITLE
Fix role granting for custom roles

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1895]
There is an issue preventing a namespace admin from doing rolebindings for the custom roles created
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1050

- [x] investigate issue
- [x] test fix
- [x] roll out via CCM (if required)

**Comment by j-pye** [comment]
Waiting for feedback.

https://github.com/bcgov-c/platform-gitops-gen/pull/313

**Comment by IanKWatts** [comment]
@NickCorcoran  I've been assigned this ticket now and would like to know if the requirements have changed or not.  My understanding is that the `user-admin` role, which exists in all clusters, is not ideal, because it allows users to grant themselves additional roles, such as `admin`.  Are we still looking for a more secure option that will allow namespace admins to create RoleBindings for their custom Roles?

**Comment by IanKWatts** [comment]
These custom ClusterRoles are not used and no longer needed.  AG, which had a special interest in this functionality, can now manage their RBAC with ArgoCD where these permission concerns are not an issue.  Closing this ticket.
