### ISSUE TITLE
User research and engagement - Review research to date

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#1927]
**Describe the issue**
We need to identify the gaps that exist between the current research and the research needed to create and user-centred content strategy and IA. There's a lot of research already, so we'll go through that to see what's there and how it meets our needs (or doesn't)

**Additional context**
These are the resources we have to date:
[Private cloud service blueprint](https://app.mural.co/t/platformservices5977/m/cloudpathfinder2329/1612805170526/e783ab82c0e658a661f97431218df00858efffe9?sender=uf88144ee66b054ae5c871382)
[Onboarding research analysis](https://app.mural.co/t/platformservices5977/m/platformservices5977/1632431504450/b95cf2daec2d23d395846f61fe056991bb9491e5?sender=udb0eaba57bd3b9a2fa8e3916)
[Service overview](https://docs.google.com/presentation/d/1ItipubvqCR1rI_VVVbx_swX659HPgN_tiwiKJp1eL94/edit#slide=id.gbdc1011b6a_0_517)
[Platform challenges](https://docs.google.com/presentation/d/1_V2hQv-wW4FiClZ3T9IPXTs8CbS3KlQUdCTPYOjod00/edit#slide=id.p1)
[BMC workshop preso](https://docs.google.com/presentation/d/1wccNb90inALBbeySerbZLMqkbVjhQmJQsxZ0xpyAC4c/edit#slide=id.p1)
[Developer experience challenges poll](https://docs.google.com/spreadsheets/d/1uVKwFSmfpEdAPvo17DLJ_VkLLKi2yOCod1E7hkiX4FU/edit#gid=0)
[Raw data from BMC workshop](https://docs.google.com/spreadsheets/d/1WZeA8Ffk-0WyLOqp5ht5WvGH_XENFJV3nFsZo7MclSo/edit#gid=1189636354)
[Private cloud BMC](https://app.mural.co/t/platformservices5977/m/cloudpathfinder2329/1616704079748/fe26c5ca20ed0cdbc651f60b2370db708d34a9f0?sender=udb0eaba57bd3b9a2fa8e3916)
[Service blueprint](https://app.mural.co/t/platformservices5977/m/cloudpathfinder2329/1612805170526/e783ab82c0e658a661f97431218df00858efffe9?sender=udb0eaba57bd3b9a2fa8e3916!)
[Bjorns Experience DevOps Journey Map-smallResolution (1).png](https://images.zenhubusercontent.com/619e7c0917f0b96bbcf6d42f/0519eb43-06ed-4e6a-8c4e-c2446ec6a2d8)
[Roadmapping prioritization community engagement](https://app.zenhub.com/files/220104031/9f7c208d-15c1-48ee-970f-30721be6e2c7/download)
[DevOps platform workshop voting](https://app.zenhub.com/files/220104031/e15bd0b0-8463-42d8-89c0-fa85056022d1/download)
[Product Owner platform workshop voting](https://app.zenhub.com/files/220104031/179f11e3-6626-4f8d-91eb-9b8b275132e8/download)
Onboarding email that Olena sends out (below in the comments)
[Private Cloud as a Service/Openshift Platform Service Overview](https://developer.gov.bc.ca/Service-Overview-for-BC-Government-Private-Cloud-as-a-ServiceOpenshift-4-Platform) (plain language one pager)
[Private Cloud as a Service/Openshift Platform Service Definition] (https://developer.gov.bc.ca/BC-Gov-PaaS-OpenShift-Platform-Service-Definition) (a more detailed technical overview)
[Onboarding Guide onto the BC Gov’s Openshift Platform for new Product Teams] (https://docs.google.com/presentation/d/1UcT0b2YTPki_o0et9ZCLKv8vF19eYakJQitU85TAeD4/edit?usp=sharing)
Developer Experience - Challenges Poll.xlsx
Public cloud personas.pptx
RoadmappingPrioritizationCommunityEngagement_participants_2021-06-22_19_00_02.xlsx

**Definition of done**
- [x] Research is reviewed and notes taken in a document, spreadsheet, or Mural

**Comment by theresawuzhere** [comment]
Here is some reading material for your team in preparation for the onboarding meeting that may answer some of the questions that you have:
Private Cloud as a Service/Openshift Platform Service Overview
(plain language one pager) Private Cloud as a Service/Openshift Platform Service Definition
(a more detailed technical overview)
* Onboarding Guide onto the BC Gov’s Openshift Platform for new Product Teams

The best way to see Openshift in action is through the free training that the Platform Services Team provides to new teams: Openshift 101. I will check when the next session is scheduled and let you know (tentatively it is Oct 20th).

Once your team had a chance to meet with me to talk about the roles and responsibilities for the product teams working on the Platform, we can provision a project set for you in our Openshift 4 environment via the Platform Project Registry

and you can start learning the technology hands-on.

In order to connect with the Platform Community in RocketChat
, you will need to have your GitHub IDs (make sure 2FA is enabled on the account) added to bcgov and BCDevOps orgs in GitHub (if you send me the list of IDs I can do it for you) . You will need to accept the membership invite from GitHub and will be able to access to the RocketChat after that. Read about channel conventions here
.

**Comment by theresawuzhere** [comment]
Here is the [research review document](https://docs.google.com/document/d/1t_8PSJ1Tx5wwuSEiuCp7EwTgKiudioggTfXYQApXWhg/edit?usp=sharing)

There's a lot here to put into the proto-personas and identify the gaps. There's a lot of material to work with, especially around the developer persona.
