### ISSUE TITLE
Sysdig PVC data

### ISSUE THREAD

**Issue by jlangy** [BCDevOps/developer-experience#1983]
**Describe the issue**
I would like to track whether our PVCs in openshift are approaching capacity through sysdig alerts

**Additional context**
In sysdig we have data for some of our PVCs coming through, but others have no information. We would like to be able to track how full some of the PVCs are that are missing from sysdig are.

**Definition of done**
Understand what is necessary to send PVC data through to sysdig

**Comment by ShellyXueHan** [comment]
### Updates:

Have had several discussion and troubleshoot with Sysdig support. So far we know:
- kubelet service metrics endpoint is working fine
- we have no problem querying PVC metrics from prometheus
- sysdig not complaining about kubelet service connection
- no other sysdig error message related to this

In a nutshell, we need to dig down on this issue further. No estimation at the moment as we don't know what the cause is.

Suggestion for now is to monitor pod disk fullness which includes PVC usage. Note that this is not an accurate reflection of the actual usage percent, but more of an similar approach.

**Comment by jlangy** [comment]
Thanks for the update @ShellyXueHan, for the disk fullness were you using `fs.used.percent` in sysdig?

**Comment by ShellyXueHan** [comment]
yes and there's `fs.bytes.used` & `fs.bytes.free` as well. But i think they are just the same thing

**Comment by ShellyXueHan** [comment]
### Updates:

We found out that the issue is because we enabled Service Discovery recently, which makes sysdig to use `promscrape.v2`. For sysdig to get kubelet metrics (including PVC ones) again, we need to work on some prometheus config changes. That is in progress at the moment, but we’ll have to disable Service Discovery for now.

**Comment by jlangy** [comment]
Thanks @ShellyXueHan, with service discovery disabled should that work for promql kubelet queries again? e.g `kubelet_volume_stats_used_bytes`, I was trying that out but is giving no data, will it need the prometheus config changes first?

**Comment by ShellyXueHan** [comment]
@jlangy the config has not been pushed to silver yet as all changes were paused during holiday season. The next ccm push will be next week. Once that's in I'll let you know!

**Comment by ShellyXueHan** [comment]
### Update
PVC metrics is available now in silver.
