### ISSUE TITLE
Investigate support options and needs - Mobile app support

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#2075]
Connect to discuss opportunities.

**Comment by ShellyXueHan** [comment]
Since we are getting a mobile team later in April, let's not make all the trouble for Bruce and Nick to take this on. Mobile support typically takes me 1-2 hours per sprint, including meetings and technical tasks, which is reasonable work load for operations so we are good to keep how it is for now! Since this is not a critical service, discussed during sprint planning that we should be okay to keep this level of support for now.
