### ISSUE TITLE
VuePress PoC

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2141]
Platform Services Team is looking for a product that can replace DevHub as a content management system for technical docs that are stored in DevHub. The CMS should meet the requirements outlined in [this ticket](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1349)

We like the [tech docs site](https://docs.cloud.service.gov.uk/) that UK gov built and ideally want something very similar.

Additional consideration: We plan to use WordPress for [our "business" website](https://platform-services-dev.apps.silver.devops.gov.bc.ca/) so would be good to know if VuePress can or cannot integrate with WordPress.

**Note: Cloud Pathfinder ran a PoC to test VuePress with the Openshift 101 content. See the results [here](https://unoah.github.io/cloud-pathfinder/openshift101/00_overview.html#special-notes).**  
DoD:
- [ ] have a [VuePress](https://vuepress.vuejs.org/guide/getting-started.html#quick-start) installed in a `ee74a4-dev` in KLAB and assess how it meets the requirements above. 
- [ ] Assess if the VuePress site can be integrated with KeyCloak SSO for user authentication as per [this article](https://auth0.com/blog/vuepress-authentication/) If it can, we will be able to retire Documize and have one doc location!
 - [ ] Document the assessment results in this ticket and present at a Team Huddle

**Comment by mitovskaol** [comment]
@juhewitt ^^^

**Comment by ty2k** [comment]
Here are my research findings for how Vuepress might act to replace [devhub-app-web](https://github.com/bcgov/devhub-app-web):

Vuepress is a static site generator that uses the Vue.js front-end framework to build a site from a series of Markdown documents. It includes options for customizing look and feel through configuration options and plugins. It is commonly used for documentation sites in a monorepo format, where all of the target documents are kept right in the repository alongside the Vuepress configuration.

Looking at the [DevHub Ecosystem Diagram](https://github.com/bcgov/devhub-app-web/blob/master/schematic.md), Vuepress is a candidate for replacing the "DevHub App Frontend" block, where [Gatsby](https://github.com/gatsbyjs/gatsby) now resides:

![DevHub ecosystem diagram](https://user-images.githubusercontent.com/25143706/151282518-7331c27e-8e27-4a1a-b832-046ec1bad895.jpg)


Gatsby has very similar features to Vuepress, but it uses the React front-end framework rather than Vue.

In terms of individual requirements for a DevHub replacement:


## GitHub integration and ability to pull content from multiple repos

Much like we are using DevHub now, we would have to add the functionality to pull from multiple repos ourselves if we were to swap Gatsby out for Vuepress. This requirement is a complicating factor for any CMS solution, as it's not a standard pattern for documentation sites built using static site generators. The more common monorepo approach means a merged pull request in the repository kicks off a new build automatically.

To support content freshness across multiple repos, we could:
- Use a scheduled cronjob to regularly re-build the app with up to date content (we do this now with DevHub). This approach doesn't give us automatic/instant updates when a source repo gets updated.
- Add custom logic to watch for updates on disparate GitHub repositories. Ideally, this could happen through some kind of push notification from GitHub, which could kick off an automatic update.
- Do something else.


## Searchability - robust search engine

Vuepress includes a simple search, but it only indexes document titles, H2 and H3 tags, and tags added in Markdown front matter [(source)](https://vuepress.vuejs.org/theme/default-theme-config.html#search-box). The Vuepress docs specifically mention Algolia as a solution for full text search.

Robust search is another feature we would have to build ourselves, as we've done with our Algolia integration in DevHub now.


## Easy to use interface to organizing content and the layout

Vuepress and Gatsby are equally capable of this. It will be up to us to decide on layout and content organization using either framework. The left hand ordered list navigation from Vuepress or [GOV.UK Developer Docs](https://docs.publishing.service.gov.uk/) can be accomplished with either site generator.


## WordPress integration

There isn't a built-in integration available. WordPress does have a REST API that could be accessed from a static site created by Vuepress or Gatsby. It would be necessary to build this ourselves for whatever static site generator we are using.


## Keycloak SSO integration

No built-in integration exists. Similar to the Keycloak integration that has been added to DevHub, we would be building this ourselves. Because Vuepress controls the application routing, an integration like the one linked in the ticket ([Authenticating Vuepress Apps with Auth0](https://auth0.com/blog/vuepress-authentication/)) would be used for hiding blocks of content within a page that any user can access, as opposed to redirecting non-authenticated users to a login page as you would expect (like with Documize now).


## Overall impressions

Swapping out Gatsby for Vuepress within our DevHub application would be a lateral move that doesn't give us clear benefits. Given the size of our dev team, we would want to carefully decide whether we should introduce Vue or Angular front-end dependencies in our stacks. These frameworks are great, but having to switch between frameworks when moving from app to app could slow us down and limit code re-use.

For any DevHub replacement, we should carefully weigh the requirements for supporting multiple repositories and for public and private content on the same site. For example, if we ended up with two simple static sites, one totally public (public repo and public site content) and one totally private (private repo and public site with all routes behind authentication), we could potentially end up with much easier maintenance and fresher documentation (due to lower barriers to contribution).
