### ISSUE TITLE
Document Openshift 4.8.28 Upgrade Post Mortem

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2244]
There were multiple issues that happened during the Openshift 4.8.28. We would like to document them including the resolution process to share with the Community.  

DoD:
- [x] Document the event log for the Openshift 4.8.28 including identified issues, troubleshooting efforts and fixes.

Olena: based on what I saw in Rocketchat, the following services were impacted:
- **Issue**: kubelet service over loaded during the cluster upgrade. **Root Cause:** TBD, possibly linked to the AQUA behaviour during the upgrade.  It seems that the code added in k8s 1.21 to better track file usage was struggling to count/stat the dozens of lock files created by AQUA during the upgrade, leading to high CPU usage in the kubelet. The cases are open with RedHat and AQUA for investigation.
- **Issue**: Sysdig started firing multiple alerts and the alert level had to reduced by teams to avoid being spammed. **Root Cause:** It seems to be linked to the kubelet overload issue. **Resolution:**  Once the kubelet issue is resolve, Sysdig alerts should go to the normal level.
- **Issue**:  Some Patroni clusters went offline. **Root Cause:** There was a bug in the default health checks in Patroni `1.6.5` that made it vulnerable to node restarts during the upgrade. The teams that had developed custom health checks were not impacted.  **Resolution:** The upgrade to Patroni `v2.0.1` fixes the issue.  @caggles  can you please correct this/fill in missing info.
- **Issue**:  AQUA agents created to many lock files during the upgrade. **Root Case:** TBD.

**Comment by StevenBarre** [comment]
## Large number of failed probes (Readiness and Liveness) 

Between 09:50-10:00 on Monday morning as the control plane was upgraded we saw a large spike in probe failures.

![image](https://user-images.githubusercontent.com/24236108/154160359-0024aeff-a3eb-466e-9cb3-14582facde20.png)

https://access.redhat.com/support/cases/#/case/03143856

Some of the logs point to pods "reattaching to SDN" and some just show "context deadline exceeded"

At this point we are still unsure of the root cause. Initial debug dumps from the cluster uploaded to the case have not proven helpful.

## Sysdig hammering the API server

On Monday afternoon CCM was synced. This included an upgrade of the Sysdig agent, and enablement of a new feature. While investigating the first issue (with probes) we passed an API audit log to Red Hat. They then identified that the Sysdig service account was making a large number of requests that were being rejected (403). This was traced to missing ClusterRole / ClusterRoleBinding needed by the upgraded Sysdig and its new feature.

Tuesday morning, we applied the missing CR/CRB to the silver cluster. Immediately the API server started to struggle as Sysdig was now pulling large amounts of data from the API server. We could see it was now generating mostly `200 OK`, with some `503 Service Unavailable`. 

![image](https://user-images.githubusercontent.com/24236108/154163770-8f3bf87a-09ef-4b24-8265-a8438524e652.png)

![image](https://user-images.githubusercontent.com/24236108/154168094-ffea941c-c194-4345-93ac-7e96fbbbd132.png)

We then disabled the new feature in Sysdig `promscrape` and the API request rate returned to normal.

@ShellyXueHan has an open case with Sysdig to understand why that feature causes 250 calls to the API per second. Current theory is Sysdig was missing the ability to create `leases` so it can keep track of which worker is fetching from the API.

## Failed OS pivot

Tuesday evening after the Sysdig issue had settled down, worker nodes were again being drained, patched and rebooted. One node however got stuck on the reboot. Logs indicated it had failed to "pivot" from one OSTree to the new one. Wednesday Morning we worked with Red Hat and got it unstuck and the node rebooted onto the new OSTree.

## High Kubelet CPU usage

After solving the OS pivot on Wednesday morning, we started to take notice of alerts from the cluster of excessive memory usage on the upgraded nodes. Several nodes were pushing past 200G of memory consumed by the `kubelet` service. Further inspection found `kubelet` was also using 10+ cores of CPU (of the available 32 on a node).

With direction from Red Hat we restarted the `kubelet` service. This freed up the memory, but it began to climb again. We continued troubleshooting and had some confusion around if any of the previously mentioned issues were part of this.

Eventually we tried draining a node of all user workloads, and removing the Sysdig pod. The node still had 800% CPU usage (8 cores) from the `kubelet` and climbing memory usage.

We created a cronjob to restart the `kubelet` on all the upgraded nodes every hour on at 50 minutes to keep it in check overnight.

![image](https://user-images.githubusercontent.com/24236108/154168376-cedd08d3-94ac-4be6-a98f-1eef39d4361e.png)

After much work from the team and Red Hat we've narrowed down the issue. Somehow, the Aqua agent pod is generating a large number of lock files in `/var/log/pods/<namespace>_aqua-agent-<podid>/` . We are unsure how it's possible to create files in the log directory.

K8s v1.21 has added some new code related to calculating on node disk usage of pods. RH has reproduced the issue by adding lots of files to the pods log folder, but no issues adding to the subfolder for container logs. Removing the Aqua agent (and its files) clears the issue. https://github.com/kubernetes/kubernetes/pull/97042

@ShellyXueHan has a case open with Aqua . Red Hat is looking into why the code that collects metrics on that path seems to be inefficient and leak memory.

https://access.redhat.com/support/cases/#/case/03146251 is open with Red Hat

## Patroni image missing from Docker Hub

User reported that after one of their pods was restarted during a drain, it was unable to pull `docker.io/bcgovdevopsps/patroni-postgres` . @caggles can give more details on the cause and resolution of this.

## Patroni health check bug

There is a bug in `patronictl list` when one of the pods in the set is in a ContainerStarting phase. https://github.com/zalando/patroni/issues/1508 that causes the command to print a stacktrace and exit with an error code. This command is then used as part of the default `/usr/share/scripts/patroni/health_check.sh` script used for readiness and liveness checks.

During node drains pods get restarted onto other nodes, and can take a little while to detatch their block volume disk from the old node, and reattach to the new node, and pull the image down. During this time the other pods in the stateful set will be getting an error from their health probe scripts. If the script is used for Liveness, the pods IPs will be removed form any service objects and after sufficient fails the pod will be restarted. Patroni may then get stuck or fail to remain HA and available as all its pods start to restart simultaneously.

We've also seen a couple cases where the PVC has not been cleanly unmounted and then fails to mount due to XFS errors. So far these all seem to be connected to restarts of nodes when we had high API load, or kubelet issues from the previous discussed issues.

@caggles is working on directions on how to upgrade the Patroni clusters to avoid this bug going forward.

**Comment by StevenBarre** [comment]
# Update

## Patroni health check bug

@caggles posted in [RC](https://chat.developer.gov.bc.ca/channel/devops-operations?msg=55Ny6shnX6Z5JHE5C) with the steps to upgrade and a warning that we'll be resuming node reboots Wednesday Feb 23rd at 9am.

## High Kubelet CPU usage

After a debug call with Aqua support and a senior engineer, RH and us believe we have found the root issue. We're now trying to convince Aqua, and get them to fix it.

The Aqua agent appears to be creating containers in its own pod, on the fly. This is working around how Kube should work and the extra containers are not visable to kube or `oc describe pod`. We believe they are using `crictl` to create the containers attached to the agent pod on the fly. These containers have their log files set to be in the root pod log folder. When the containers are then removed, the log files are left behind and never cleaned up. This is causing the large number of files that is impacting the kubelet. The log files should be stored in the agents container folder, where kubelet can then rotate and clean them up, or perhaps in `/var/lib/aquasec` .

**Comment by StevenBarre** [comment]
# Update

The resumption of the node upgrades is now scheduled for March 7th at 9am

## Large number of failed probes (Readiness and Liveness)

Red Hat continues to look into this, but it is not expected to occur again during the Silver upgrade. We'll watch this closely during the Gold upgrade.

## Sysdig hammering the API server

We attempted the fix with `leases` from Sysdig but it did not help. For now the `promscrape` feature remains disabled while @ShellyXueHan continues to work with the vendor on a long term solution.

## High Kubelet CPU usage

We've replaced our cron job that restarts `kubelet` with one that deletes older lock files from the Aqua agent directory. This seems to be as effective as the `kubelet` restarts without the downsides.

**Comment by caggles** [comment]
#Update

The last piece of missing information from this post mortem is what happened to the Postgres-Patroni image in Dockerhub. It "disappeared" from the image stream being used by several teams.

After some investigation, I found that the repository on Dockerhub was private. While an image-stream existed locally on the Openshift registry, that image-stream just pointed to Dockerhub, so users still needed appropriate privileges on Dockerhub to access it. This meant that users without authorized Dockerhub accounts (which is most users) were unable to pull the image.

It's still not entirely clear how the repositories on Dockerhub ended up private in the first place. There is no reason to believe that this was done intentionally, nor is there any evidence that this was caused by some bug in one of our automated processes. This leaves the most likely possibility - someone manually made the change, likely by accident or because they believed that they were making an appropriate and expected change.

The fix was simply to change the repos to public. We have since monitored the repos and there has been no indication of any further problems.

In the future, we should be more cautious about what we change in our Dockerhub accounts and/or to be sure to communicate any changes quickly. We are also in the process of setting up additional automated tests so that we can be informed more quickly if we lose access to an image like this in the future.
