### ISSUE TITLE
Automatically show the Eventbrite events on the WP site

### ISSUE THREAD

**Issue by theresawuzhere** [BCDevOps/developer-experience#2444]
**Describe the issue**
Automatically show the Eventbrite events on the WP site

**Additional context**
We will have [this training page](https://cloud.gov.bc.ca/private-cloud/support-and-community/platform-training-and-resources/) where we want to show the upcoming Eventbrite events. Instead of putting them in manually, we want them to appear automatically.

**Definition of done**
- [ ] Eventbrite events appear on the page.
- [ ] Events are in order by date starting with next upcoming event
- [ ] Users can click on a link to register for an individual event

**Comment by ty2k** [comment]
Eventbrite doesn't provide a plugin integration with WordPress directly. We could build our own using the [Eventbrite API](https://www.eventbrite.com/platform/api), or choose an off-the-shelf option:

![Eventbrite plugins for WordPress](https://images.zenhubusercontent.com/5ec709daacce4878764898c4/415ce037-b18e-4bab-bb55-058b47e60914)

The most widely used is a general events calendar plugin called [The Events Calendar](https://wordpress.org/plugins/the-events-calendar/) that provides a premium Eventbrite add-on at an extra cost (see USD [pricing](https://theeventscalendar.com/products/wordpress-eventbrite-tickets/)).

**Comment by ty2k** [comment]
@theresawuzhere could you please advise, will this be a new Eventbrite account that is hosting training scoped to just the Private Cloud PaaS product, or will this cover training for the other cloud teams as well? There is an Eventbrite account for the [Exchange Lab on Eventbrite](https://www.eventbrite.ca/o/exchange-lab-17002217203), and it looks like the one linked to the current [events page on DevHub](https://developer.gov.bc.ca/events). Wondering if we are re-using that account, or if there is another in the works.

**Comment by theresawuzhere** [comment]
@ty2k I believe Matt Spencer has a eventbrite account for our team. I will ask him.

**Comment by ty2k** [comment]
@theresawuzhere Thanks for passing along the Eventbrite credential. Could you please take a look the [updated Training page](https://platform-services-dev.apps.silver.devops.gov.bc.ca/support-and-community/training-from-the-private-cloud-team/) where I've added an instance of the [Blocks for Eventbrite plugin](https://wordpress.org/plugins/blocks-for-eventbrite/) to the bottom of the central content column? I haven't touched the styling or anything yet. Just want to make sure that list is going to meet your needs first.

**Comment by theresawuzhere** [comment]
@ty2k it's great. i've removed the rest of the content on the page. so now you can style it. :-)

**Comment by ty2k** [comment]
I have a page that uses the Blocks for Eventbrite plugin with some basic BC Design System styles here: https://cloud.gov.bc.ca/private-cloud/eventbrite/

Note that the page is currently set to private, so you will need to be logged in to view it.

There are no preview images displayed with the events because they are being blocked by the content security policy on the site:

![Screen Shot 2022-07-29 at 2.43.12 PM.png](https://images.zenhubusercontent.com/5ec709daacce4878764898c4/b91bd3d6-69ff-4332-a437-7ad5ca4819c7)

Instead of showing the broken image indicator, I'm hiding it with the styled yellow top border on each card.

I know GDX is reluctant to add additional Content Security Policy exceptions, as this configuration gets applied to all of their sites, I believe. In general, having a tight content security is good in WordPress land, because you want to prevent rogue plugins from acting badly, and blocking external content helps.

I see that the Eventbrite list is one of the last remaining tasks in [#2534](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/2534), so I would recommend we add it as is. The CSS styles are applied site-wide, so we can use an instance of the Blocks for Eventbrite block on pages like [Events in the BC Gov Private Cloud PaaS](https://cloud.gov.bc.ca/private-cloud/support-and-community/events-in-the-bc-gov-private-cloud-paas/) as an example.

Thoughts @theresawuzhere?

**Comment by lukegonis** [comment]
We have decided not to display events in the way described above and will link to events in Eventbrite directly from this page https://cloud.gov.bc.ca/private-cloud/support-and-community/events-in-the-bc-gov-private-cloud-paas/
