### ISSUE TITLE
Screen mockups for Security Dashboard in Registry

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2460]
We need to have a visual showing how the MVP of the Project Security Dashboard will look like in the Registry. More context about the Security Dashboard can be found in [Epic](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1710)

DoD:
- [ ] Meet with @NickCorcoran , understand what signals will be included in the MVP of the Secuty Dashboard and produce screen mockups showing how the dashboard will look like

**Comment by ShovelHand** [comment]
This is a copy/paste from what I wrote for the epic.
Just adding for the record that Nick and I have had a meeting about this. Some points:
There is a mockup above. [Not here, in the epic]
Some of these issues may be dependent on the re-write, but I think it makes sense to start looking into them sooner rather than later. There's lots I need to learn about.
Some questions at this point are what is user definable, like should the client be configuring the URL to the repo, and what do we do programatically.
