### ISSUE TITLE
Decide how/when to run Kraken going forward

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2468]
**Describe the issue**
Now that we have documented the steps to run Kraken, decide which clusters it should be run on, and when.

**Additional context**

**Definition of done**
Document the plan for when and where to run Kraken going forward

**Comment by wmhutchison** [comment]
I have no issues or concerns running Kraken against a LAB environment. Not the same when we're talking PROD. 

Overall, the one who benefits from these exercises is Red Hat who can be further fed from our Kraken test results for further identification of edge cases we seem to be so good at finding. 

Running in Kraken in PROD may result in a situation where the vendor respectfully asks us to stop "doing the thing that broke your cluster" if it turns out that a combination of factors (including SILVER's larger capacity/load) results in core services like etcd or API going down entirely.

**Comment by StevenBarre** [comment]
Ya, I would agree this likely should just be kept to lab clusters. I was thinking more along the lines of do we run this once a week? or just run it after upgrading a lab as part of the verification process?

Do we want to add in extra scenarios to test things like Vault. Artifactory, etc?

**Comment by StevenBarre** [comment]
- Document how to run Kraken on util server
  - finalize list of scenarios to run
- Run before / after lab upgrade and compare
- Demo for product teams showing how to impact their namespace / app
- Write docs for product teams on how to use kraken on their app

**Comment by StevenBarre** [comment]
Discussed the next steps for Kraken. Created new backlog tickets for those actions/deliverables.
