### ISSUE TITLE
Fix Openshift 101 Lab Content

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#2537]
**Describe the issue**
A couple of typos, confusing sections and at least one straight-up incorrect instruction has come up as part of Openshift 101 Lab. We should run through the lab and correct these issues.

**Additional context**
See: the ocp101 lab chat channels on RC - there are references to these issues in most of these channels.

**Definition of done**
- [x] Training team is able to run through the entire lab as written without issue.

**Comment by mitovskaol** [comment]
@mtspn Would you like to take over this ticket?

**Comment by mtspn** [comment]
@mitovskaol @caggles If there is some more information about the specific errors I can take this on? Otherwise I hope that my recent updates might have taken care of the problems and if so, this could be closed.

**Comment by mtspn** [comment]
The latest version of the lab exercises can be found [here](https://github.com/BCDevOps/devops-platform-workshops/tree/master/101-lab/content), in the August 101 lab I'm planning to give students the direct link to these instructions rather than have them work from the gitbook site. This will avoid the syntax highlighting problems in gitbook and make it easier for students to copy code examples.
