### ISSUE TITLE
Project Examples List (New Page)

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#2631]
Create a new page for example projects in the section **Reusable code and services** 

With following examples:

Aries Verifiable Credential Registry https://github.com/bcgov/TheOrgBook
Hired Equipment Tracking System (HETS) https://github.com/bcgov/hets
My Range Application (MyRA) API https://github.com/bcgov/range-api
Transportation Fuels Reporting System https://github.com/bcgov/tfrs

**Definition of done**

- [ ] First draft
- [ ] SME review
- [ ] Approval

**Comment by Pilargit12** [comment]
Are these the best examples to be entered in the section of tech docs called: **Reusable code and services** are they still relevant? 

Aries Verifiable Credential Registry https://github.com/bcgov/TheOrgBook
Hired Equipment Tracking System (HETS) https://github.com/bcgov/hets
My Range Application (MyRA) API https://github.com/bcgov/range-api
Transportation Fuels Reporting System https://github.com/bcgov/tfrs

**Comment by ShellyXueHan** [comment]
something else to include:
- NRN showcase app: https://bcgov.github.io/common-service-showcase/
- Gold cluster app: SSO/Rocketchat/API gateway
- most common nodejs app: one of the originally listed app
- legacy migration app (TBD)
- data analysis/AI app (TBD)
- non-custom built app (TBD)

**Comment by Pilargit12** [comment]
For the creation of this page, we'd like teams to provide us with: 

1. **Project overview:**
   - Briefly describe the purpose and goals of the project. What problem does it solve or what need does it address?

2. **Key technologies used:**
   - Highlight the main technologies, frameworks, or programming languages employed in the project. This gives readers an idea of the technical stack involved.

3. **Challenges and solutions and/or lessons learned**
   - Discuss any notable challenges faced during the development process and how the team overcame them. It provides insights into problem-solving and the team's adaptability.
   - Share insights and lessons learned during the development process. Discuss what worked well, what didn't, and any adjustments made along the way. It helps other developers avoid common pitfalls and improve their own development practices.

Very nice to have as well (but optional): 

Code Snippets:

4. Share concise and relevant code snippets that showcase interesting or innovative solutions implemented in the project. This allows developers to learn and apply similar techniques in their own work.
Architecture Overview:

5. Provide a high-level architectural overview of the project. This could include diagrams or descriptions of how different components interact. It gives insights into the project's structure in OpenShift and design decisions.

**Why would teams want to share this with us in our tech docs website?**

To entice a team to share their project:

1. **Highlight visibility:**
   - Emphasize the exposure their project will get by being featured on the Project Examples page of our tech docs and backstage.io. This can be an excellent opportunity for recognition within the community

2. **Emphasize learning opportunities:**
   - Stress the educational value for other developers. Let them know that by sharing their project, they contribute to the learning and growth of the community

3. **Networking and collaboration:**
   - Highlight the potential for networking and collaboration. By showcasing their project, they may attract like-minded individuals or even potential collaborators for future projects.

4. **Promote community contribution:**
   - Frame it as a way for them to give back to the community. If their project has the potential to inspire or help others, it can be a rewarding experience for the team to know they've made a positive impact.

5. **Provide assurance of control:**
   - Assure them that you respect their intellectual property and won't reveal sensitive information. Make it clear that the focus is on high-level showcasing rather than divulging proprietary details or details that for security and privacy reasons cannot be shared and that will be respected, if they wish for us to remove them at a later point we can.

**Comment by Pilargit12** [comment]
**For rocket.chat - message to devs** 

Hey [Developer's Name],

Hope you're well! 👋 We're fans of your work on [specific project/tech] and want to showcase it on our "Project Examples" page in our [tech docs for the Private cloud](https://mvp.developer.gov.bc.ca/docs/default/component/platform-developer-docs).

What we'd love from you:

1. Project Overview: Quick description of your project and its goals.
2.Key Technologies: Highlight the tech stack.
3. Challenges/Solutions or Lessons Learned: Share hurdles faced or valuable lessons.

Nice-to-Haves:
5. Code snippets or repo links
6. Architecture overview

Sharing can involve awesome benefits too!:

🚀 Visibility: Reach a wider audience, recognition among the community as well
🧠 Learning: Contribute to developer growth.
👥 Networking and promoting community contribution: Open doors to potential collaborations.

We respect privacy and security; focus is on a high-level showcase.

Interested?

[Your Name]

**Comment by Pilargit12** [comment]
[Adding PR # 208](https://github.com/bcgov/platform-developer-docs/pull/208)

**Comment by ShellyXueHan** [comment]
### Updates:
- we have reached out to 3 teams, waiting for response on timeline and project info

**Comment by Pilargit12** [comment]
Teams that will be included: 

- Digital minds team
- SSO team
- Registry team

**Comment by Pilargit12** [comment]
* Emails requesting teams to complete request by Feb 10 - sent to MDS and SSO sent today

* @ShellyXueHan to be in touch with Product registry team

**Comment by Pilargit12** [comment]
No response from all three teams - sent another reminder to all of them today Jan 23, 24. Hoping to get a reply. If not, we need to circle back  and decide next steps.

**Comment by Pilargit12** [comment]
SSO team (Single-Sign-On) - Samji Zorin (product owner) - replied advised they will do their best for Feb 10

**Comment by ShellyXueHan** [comment]
### Updates:
- we've got docs ready for review from SSO team and Registry team
- we'll reach out to the GOV Website Content Management Framework team as a third example

**Comment by Pilargit12** [comment]
Update: 

- Completed the first two project examples - waiting to merge

Next: 

- **GOV Website Content Management Framework**
      PO: ian.hallas@gov.bc.ca
      best tech person to reach out for doc: chris.1.mullin@gov.bc.ca
