### ISSUE TITLE
Implement relative links to Tech Doc site pages in WP

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2662]
Our private cloud site in WordPress contains many links to pages in the Tech Doc site. As we are looking to launch the Tech Doc site using a temporary URL and change it to a permanent URL later, we want to be able to store the Tech Doc site domain in an environmental variable in WP and read it from there when generating a full URL at deployment time.

For example: Instead of using `https://beta-docs.developer.gov.bc.ca/page1` as a link on a WP page, it would be `<TECH_DOC_SITE_DOMAIN>/page1`. 

DoD:
- [x] Implement the ability to pull the domain name for Tech Doc Site from an environment variable or config file in WP  to add to links at the deployment time

**Comment by ty2k** [comment]
After research and trial-and-error, I have found that this "tokenized link" pattern is not easy to replicate in an automated fashion in WordPress the way it would be in other static site building systems.

The WordPress editor allows content writers to add links by searching through the current posts/pages in the WordPress site (the exact link URL is handled by WordPress with the user just selecting the post/page), or by supplying a URL directly. While the URL can accept a token, there is no mechanism built into WordPress (or any plugin I've seen) to replace the token with an environment variable, the way we are doing in Gatsby (see #2672).

Adding a link by URL:
![](https://images.zenhubusercontent.com/5ec709daacce4878764898c4/f82a8265-83b1-416b-b423-459457087e91)

Adding a link by search term:
![](https://images.zenhubusercontent.com/5ec709daacce4878764898c4/5b115e5f-fd7a-434b-b2e3-529fb4105225)

This makes sense, as WordPress is a stateful CMS with its own content promotion patterns baked in. Rather than promoting content-as-code through different development environments, content goes into the production database and gets published from there based on WordPress' state.

As a work-around for this functionality, we can use the text replacement feature of the All-in-One WP Migration plugin **at export time** to replace the Tech Docs site URL with another target. You can see this working with the "Sysdig Monitor" page in the [dev](https://platform-services-dev.apps.silver.devops.gov.bc.ca/our-products-in-the-private-cloud-paas/monitoring-with-sysdig/) and [test](https://platform-services-test.apps.silver.devops.gov.bc.ca/our-products-in-the-private-cloud-paas/monitoring-with-sysdig/) instances, with the "Sysdig technical documentation" link 2/3 of the way down the page. In dev, we are pointing to the `-dev` OpenShift namespace, and in test, we are pointing to the production URL `beta-docs.developer.gov.bc.ca`. The URL replacement pattern was specified while doing an export of the dev content - there is no visible mechanism in the UI to specify a replacement at import time.

![All-in-One WP Migration export screen](https://images.zenhubusercontent.com/5ec709daacce4878764898c4/2f57c28f-7e20-4456-b54b-9efd6cd21ebf)

Given that we will be adding content into the production site and only copying back to `-dev` or `-test` as needed to work on code, I feel that this should be sufficient for our needs. Content editors can link to the production Gatsby site now with the `beta-docs` URL. Once they are given access to the production WordPress site, all new content should be created there, with new links pointing to `beta-docs`.

@mitovskaol please advise if this is sufficient or if there are more exotic/on-going requirements you have in mind for this feature.
