### ISSUE TITLE
Import redhat.io images to openshift namespace

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#277]
https://trello.com/c/BND4GuXB/118-import-redhatio-images-to-openshift-namespace

alec.wenzowski is interested in using some of the [new rhel8](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index?lb_target=stage#get_ubi_images) images that are only available via redhat.io which requires authentication.

After discussing in the [Red Hat Case](https://access.redhat.com/support/cases/#/case/02419137) it was decided the best path forward was for an admin to manually import them into the openshift project which already has authentication and let devs pull from there.

**Comment by jefkel** [comment]
I'm not sure why this is assigned to me.  

From what I can tell, this looks like a bit of an ongoing service that would need to be created to do the following:
- manage a list of RH images to be imported (how are requests to add/remove from this list accomplished? Who curates/owns the list?)
- Automate the update of the listed images
- Cleanup old images?
  - Do we force-delete images after a certain number of updates?
  - How do/can we manage version tagging to force updates by development applications?

**Comment by sbarre-esit** [comment]
> I'm not sure why this is assigned to me.

Because the Trello card was assigned to you, Phil, and Clecio

Maybe we can give this to Shelly/Cailey to handle? Or whoever handles the other bcgov images?

**Comment by wenzowski** [comment]
> alec.wenzowski is interested in using some of the new rhel8 images that are only available via redhat.io which requires authentication

No, that's not quite it. On 2018-08-23 the deprecation timeline for `registry.access.redhat.com` was announced with a scheduled decommission date of 2019-08-23. 
> The current registry, at registry.access.redhat.com, is scheduled to be retired approximately 12 months from now
– [source as captured 2018-10-05](http://web.archive.org/web/20181005001401/https://www.redhat.com/en/blog/transitioning-red-hat-container-registry)

I requested a resolution on an organizational methodology for accessing the Red Hat Container Registry when we were half way through the deprecation window, in Feb 2019.

The Red Hat team reversed their decision to decommission `registry.access.redhat.com` in [#1734715](http://web.archive.org/web/20200615192516/https://bugzilla.redhat.com/show_bug.cgi?id=1734715) on 2019-08-01 only weeks away from the scheduled decommission date. The article was adjusted in-place at this time to read:
> The current registry, at registry.access.redhat.com, will eventually be retired; however, no immediate action is required for existing OpenShift and Red Hat Enterprise Linux deployments.
– [source as captured 2019-08-08](http://web.archive.org/web/20190808105606/https://www.redhat.com/en/blog/transitioning-red-hat-container-registry)

At the time of initial report I noted that I was unwilling to redistribute restricted RHEL content to BC Gov in contravention of Red Hat's restrictive redistribution clause. Downloading restrictively licensed content from Red Hat using my personal credentials and uploading said content to `docker-registry.pathfinder.gov.bc.ca` constitutes redistribution according to advice received from counsel.

I found some resolution to my concern on 2019-05-07 when Red Hat announced `ubi8` with their new permissive license.
> This means you can build a containerized application on UBI, push it to a container registry server of your choosing, and share it.
– [source as captured 2019-08-08](http://web.archive.org/web/20190510014853/https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image)

Much redistributable content has since been cross-published from `registry.redhat.io` to `registry.access.redhat.com`, eg. `registry.access.redhat.com/ubi8/ubi` but restrictively licensed images continue to be available only via `registry.redhat.io` eg `registry.redhat.io/rhel8/s2i-base`.

The last update on this received was:
> The longer term plan is to leverage Artifactory as a caching source for the common external repositories, this will include the RH repo.
– @jefkel [on RC](https://chat.pathfinder.gov.bc.ca/channel/devops-how-to?msg=J4Spe67LYBhKCoFA6)

Per the [revised Red Hat Container Registry Authentication](http://web.archive.org/web/20200615195629/https://access.redhat.com/RegistryAuthentication) docs, a token from the [Registry Service Account Management Application](https://access.redhat.com/terms-based-registry/) would be suitable for this, but our Artifactory repositories are currently scoped by team. Is Artifactory no longer the best way forward to resolve this ticket?

**Comment by lukegonis** [comment]
closing this issue, as it will be addressed/tracked in the Open Shift 4 build out
