### ISSUE TITLE
Explore Monitoring for API service health via Prometheus

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#282]
https://trello.com/c/Dt6hctH2/43-explore-monitoring-for-api-service-health-via-alertmanager

Get some monitoring and graphs similar to what's now done in 3.11 for etcd. Should prove useful to determine a possible future bottleneck (API requests/second) and if we can tweak this limit if reached (config change, additional resources to API pods, etc).

**Comment by wmhutchison** [comment]
starting work on this now.

**Comment by wmhutchison** [comment]
Started exploration via Promethus UI of some of the defined metrics mentioned by Red Hat in their Health check report, looking first at the raw data presented to us to see what is of use for us to draw from.

Also lots and lots of reading to learn about some of the data concepts involved around Prometheus and some of the data types presented to us which will also in turn drive what we can potentially obtain from Prometheus via Grafana dashboards.

Aiming to start carving out specific PromQL queries to implement in Grafana next week in order to start building out new dashboards for improving our visibility into our Openshift cluster's health.

**Comment by wmhutchison** [comment]
have not made any progress on this this week due to other priorities - aim to get back on track this Friday and continue working on it next week.

**Comment by wmhutchison** [comment]
issues related to OCP PROD upgrade and other general operations support requests via Rocket chat have prevented me from resuming work on this, next week should be better.

**Comment by wmhutchison** [comment]
No time this week as well to work on this in any capacity, priority has been given over to operational issues involving NetApp block storage, where a lot of work up front is required for scaling up all of the required vendor tickets and initial data feeds.

Also on vacation starting tomorrow, back on October 19th.

**Comment by sbarre-esit** [comment]
https://sysdig.com/blog/monitor-kubernetes-api-server/

**Comment by sbarre-esit** [comment]
Latency per verb
```
(histogram_quantile(0.9, sum(rate(apiserver_request_latencies_bucket[5m])) by (verb,le)) / 1e+6)
```

API Requests per second
```
sum(rate(apiserver_request_count{code=~"2.."}[5m])) # All 2xx coded requests
sum(rate(apiserver_request_count{code=~"5.."}[5m])) by (code) # Errors
sum(rate(apiserver_request_count{code!~"2.."}[5m])) by (code) # All non 2xx requests
sum(rate(apiserver_request_count{code=~"2.."}[5m])) by (verb) # All 2xx requests by verb
```

**Comment by mitovskaol** [comment]
The decision is to use Sysdig for this kind of monitoring vs Prometheus so closing this ticket as no further research is required.
