### ISSUE TITLE
Review OCP 4.10 Release Notes - Cailey

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2942]
**Describe the issue**
Review the [OCP 4.10 Release Notes](https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html) for any changes that will impact the product teams, ops team, or platform services team. Also look for any exciting new features that community should know about.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Read the release notes. Add any bits you find interesting and needing of discussion as comments here.

**Identify any dependencies**
None

**Definition of done**
Fully read the release notes and added anything of interest as a comment here.

**Comment by caggles** [comment]
- Looks like we no longer need to explicitly specify the URL for the RedHat image registry if building on a reference image from there. Not a breaking change or anything, but it's convenient.
- Non-sidecar Jenkins templates are being deprecated. Not strictly relevant to us, since this is technically only for the bundled Jenkins images, but it might be worthwhile to generalize as "RedHat's recommended way of running Jenkins has changed" in order to further encourage teams to improve their Jenkins deployments (or switch to something else).
- Grafana and Prometheus UIs are being replaced by a page on the console.
