### ISSUE TITLE
Test and merge the Developer Simulation Tool

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#304]
https://trello.com/c/Aly06hBh/143-test-and-merge-the-developer-simulation-tool

Tool to run during upgrading the Lab to generate some load and watch for issues that may affect devs during the upgrade of Prod
https://github.com/bcgov-c/platform-ops/pull/42

**Comment by tmorik** [comment]
Running tests on Lab env...

**Comment by tmorik** [comment]
Testing has been run on the Lab, feedback of one issue - one of created pod has been crashing during/after the playbook run - asking on the github [Developer simulation tool #42](https://github.com/bcgov-c/platform-ops/pull/42) if this is expected behavior.  

The provided playbooks themselves have been run with no error/warning messages.

**Comment by tmorik** [comment]
Test has been done on the Lab successfully --> https://github.com/bcgov-c/platform-ops/pull/42#issuecomment-668892401

Waiting for marge to the master.
