### ISSUE TITLE
Fix Vault Test Pods

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#3235]
**Describe the issue**
During the Vault outage, one of the vault test pods was indicating that it could not connect to the vault service. This turned out to be a problem with the pod and not the service, but was very misleading and caused us to spend a bunch of additional time troubleshooting the service unnecessarily.

**How does this benefit the users of our platform?**
A properly functional vault test pod will allow us to more effectively be alerted in the event of a problem with Vault, so we can begin taking action more quickly.

**Definition of done**
- [x] Vault test pods in the silver/gold connect to the production Vault service and can be used to test the service's availability quickly and easily
- [x] Vault test pods in klab/clab connect to the lab Vault service and can be used to test the service's availability quickly and easily
- [ ] Documentation on the existence and use of these test pods is added to both the general Vault docs and the Vault troubleshooting docs for DXC.

**Comment by ShellyXueHan** [comment]
@caggles the issue with vault testing pod is due to some extra egress netpol (they should only exist in emerald and klabs, but not the other ones). I've removed them and things are back to normal now, see PR here: https://github.com/bcgov-c/tenant-gitops-ea8776/pull/6

There are some follow up tasks we should do:
- improve documentation for sure!
- setup notification from vault testing to alert us when it's not running properly
