### ISSUE TITLE
SSO migration - Cloud Doc Website

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3257]
**Describe the issue**
This is to update the service's SSO integration to use Gold Keycloak. Migration plan has been defined previously.

**Identify any dependencies**
#3202

**Definition of done**
- [ ] update SSO integration in lower environments (dev/test/lab/etc.)
- [ ] define testing tasks to verify migration result
- [ ] define roll back plan
- [ ] community announcement
- [ ] run migration scripts if needed
- [ ] update production SSO integration and carry out testing tasks

**Comment by ty2k** [comment]
Shelly, Zhanna and I met this morning to go over the two different SSO integrations in our WordPress environment, and we determined that since we are already using the Gold Keycloak domain `https://loginproxy.gov.bc.ca` in our [Private Cloud site](https://cloud.gov.bc.ca/private-cloud/) (an instance provided by the GDX Digital Engagement Solutions team), and using Azure AD in the [SaaS team's site](https://cloud.gov.bc.ca/saas/) (an instance where Dan Hirner and I are administrators), there is no action needed for this ticket.
