### ISSUE TITLE
IDIR accounts for PO/TLs are provisioned with admin access to the project namespaces in Openshift

### ISSUE THREAD

**Issue by ShovelHand** [BCDevOps/developer-experience#3276]
Additional Context
https://github.com/bcgov/platform-services-registry
Related to task #2247, wherein GitHub identities are to be replaced with Idir identities
DOD:
- [ ] IDIR accounts for PO/TLs are provisioned with admin access to the project namespaces in Openshift

Spun off from #2247, to break that big ticket down into just changes to the application itself.

**Comment by IanKWatts** [comment]
@ShovelHand This PR updates the app-provisioner build so that IDIR accounts (email addresses) will be included in namespace RoleBindings in addition to GitHub IDs.  However, NSX clusters (Emerald and KLAB2) will include only the IDIR accounts in the RoleBindings.
https://github.com/bcgov-c/devops-fulfillment-pipeline/pull/142

**Comment by ShovelHand** [comment]
Thanks, Ian!
