### ISSUE TITLE
OCP 4.10 Upgrade NetApp Trident in KLAB2

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3355]
**Describe the issue**
Upgrade Trident based on testing in LAB clusters.

**Additional context**
https://github.com/NetApp/trident/releases

**Definition of done**
- [ ] Trident upgraded

**Comment by wmhutchison** [comment]
Ran into issues upgrading Trident for a couple of days due to newer Trident version needing to be allowed to download images from a different repository source. INC0075193 opened to track this issue, and the net result was multiple attempts since the new remote registry had put in an undocumented redirection that is not documented, thus needing to ask DXC F5 multiple times to add new URLs ahead of the normal iStore paperwork that is required.

Appears to be now working, but will need to re-run the Trident playbook to ensure everything  that needs to be done is in fact done.

**Comment by wmhutchison** [comment]
Playbook re-ran, tested to confirm Trident still functions, closing ticket.
