### ISSUE TITLE
Vault - explore dynamic secret [spike]

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3395]
**Describe the issue**
https://developer.hashicorp.com/vault/tutorials/getting-started/getting-started-dynamic-secrets

More info: #3269

See comment below for results of the investigation.

**What is the Value/Impact?**
- enable DB secret rotation for better security

**Definition of done**
- [x] explore

**Comment by IanKWatts** [comment]
For more info, see: https://developer.hashicorp.com/vault/tutorials/db-credentials/database-secrets

**Comment by IanKWatts** [comment]
Will also require an update here: https://github.com/bcgov-c/terraform-vault-module/blob/main/main.tf

**Comment by IanKWatts** [comment]
I met with Hashicorp and one of their architects to discuss the use of dynamic secrets for databases.  Here are some of the details of that conversation:

**Separate Namespaces**
The use of dynamic secrets in Vault requires namespace-level configuration for the database connection.  In order to make this feature available to our users the only practical path would be to give them their own namespace.  Currently we use just one namespace ("platform-services") and each project set has its own secrets engines, which are KV2 and associated with their role.

So the main concern of offering this feature would be the migration to per-project namespaces:
- License would not be affected, because new namespaces would be "under" the platform-services namespace and this would not affect our user count.
- Terraform changes include:
    - Add namespace check/creation to the pipeline
    - Add 'namespace' field to the Vault Terraform provider
- There are two options for migrating secrets:
    - Use Terraform to move them
    - Move the mounts
        - https://developer.hashicorp.com/vault/docs/concepts/mount-migration

**DB Management**
In order to manage DB users in the DB itself, Vault needs root-level access.  Rather than give Vault THE root password to the DB, users would create a new privieleged account for use by Vault.  Vault can rotate this password, too, to minimize any risk associated with the privieleged account.

**Vault Offline**
The database itself does not have any knowledge of password expirations and rotations, only Vault does.  This means that if Vault is offline at a time when passwords would normally expire and be replaced, nothing happens.  The DB accounts continue to work, they just don't get rotated, so there appears to be no particular risk associated with Vault failure or failover.

**Action Item**
If we decide to pursue this feature, they recommend that we do a POC.  It might look something like this:
Select a lab project set that is already set up with secrets in Vault
- Manually create a new namespace under platform-services
- Migrate secrets to the new namespace using one of the two options described above
- In the new namespace, enable a dynamic secrets engine - postgres would be a logical choice
- Create a new privileged user, configure the DB connection, test the DB/app
- Test again using the other migration option
- Look at exactly what would have to change in our Terraform automation for a production migration
