### ISSUE TITLE
Private cloud doc - how to migrate application between OCP clusters

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3935]
**Describe the issue**
There are teams asking to move from Silver to Gold or Emerald. We don't have any offical process in the private cloud website yet. Let's add something in.

**Definition of done**
- [x] create doc
- [x] review
- [ ] added to wordpress website

**Comment by Pilargit12** [comment]
Please contact me through my work email address:
***@***.***

Thank you for making this change to this email thread

Pilar

**Comment by ShellyXueHan** [comment]
Okay here's my draft, I'm try to match up to this page https://cloud.gov.bc.ca/private-cloud/our-services-in-private-cloud-paas/get-started-with-the-private-cloud-paas/:

# Migration between OCP clusters on BC Gov Private Cloud PaaS

Are you a team working on OpenShift cluster already? If you are just looking to get onboarding, please visit [this page](https://cloud.gov.bc.ca/private-cloud/our-services-in-private-cloud-paas/get-started-with-the-private-cloud-paas/).

Do you have specific infrastructure need that the current cluster can't fulfill? Maybe it's time to move to another OpenShift hosting tier! Learn how to start the migration between different OCP clusters.

On this page

- What you’ll need to initiate a migration
- Step 1: Attend a migration assessment meeting
- Step 2: Set up your access to the new OpenShift cluster
- Step 3: Migrate applications
- Step 4: Retire workloads remaining from the old cluster
- Related pages


### What you’ll need to initiate a migration

Before starting a migration, first get familiar with the different Openshift hosting tiers. You can find out more information [at this link](https://cloud.gov.bc.ca/private-cloud/our-products-in-the-private-cloud-paas/silver-and-gold-tier-platforms/). Please note that, included in the link, there are corresponding requirements per cluster for your team to meet before moving the application workload there. Once you are clear on which cluster you'd like to migrate to, continue to the next step! If you think it's necessary to migrate your application to a higher hosting tier but your team does not meet the requirements, please feel free to reach out to us at PlatformServicesTeam@gov.bc.ca to discuss how to acquire knowledge/skill.

### Step 1: Attend a migration assessment meeting

If your team is interested to migrate to another OpenShift cluster, the first step is to request a meeting with the Platform Services Team.

During the meeting, you’ll get an overview of the different hosting tires from BC Gov Private Cloud PaaS, including what we do to support the platforms. You’ll also learn what your responsibilities will be as a product team working on the different cluster.

Here are some of the main topics to cover:
- the specific infrastructure need that you are looking for from a different OCP cluster
- which OCP cluster would be the best option
- an assessment on your team and application to determine if you are ready to move on towards a higher hosting tire
- migration timelines and follow up actions

Email PlatformServicesTeam@gov.bc.ca to request a meeting. 


### Step 2: Set up your access to the new OpenShift cluster

Once the assessment meeting is completed and your team is ready to move on, you can start a new project set request at [Product Registry](https://registry.developer.gov.bc.ca/).

Please make sure to include the following information in the request:
- the new project set name should match with the old one
- pick the OCP cluster as discussed from the assessment meeting
- by default your new project set will start with a small quota set. If you have successfully requested a quota increase in your current project set already, please mention this in the new quota request once the new project set is ready! This way you do not need to go through a quota review meeting again!

Please note that Gold and GoldDR clusters share the same authentication process as Silver, find out more information [here](https://cloud.gov.bc.ca/private-cloud/our-services-in-private-cloud-paas/get-started-with-the-private-cloud-paas/#Step-2:-Set-up-your-accounts). However, if you are migrating to Emerald, BCGOV VPN access is required. Find out more information [here](https://cloud.gov.bc.ca/private-cloud/our-products-in-the-private-cloud-paas/silver-and-gold-tier-platforms/#emerald-hosting-tier).


### Step 3: Migrate applications

Depending on the cluster picked, the migration path and requirements are very different. The Platform Services Team is responsible to provide the OCP platform infrastructure and the shared services, but it's your responsibility to update the application to work on the new clusters.

For example, the Gold cluster comes with a Disaster Recovery cluster as GoldDR. The two clusters are geographically redundant, when an cluster wide incident happens on Gold, traffic to applications will be automatically redirected to GoldDR by the GSLB. However, you need to design the DR strategy for you application, and set them up so that your workloads can benefit from the cluster failover to achieve better service availability.

There are detailed documentations and how-to guides about working on different OCP clusters in the [IDIR protected content](https://cloud.gov.bc.ca/private-cloud/idir-protected-content/). You are highly encourage to leverage the information there to modify your application for the migration.


### Step 4: Retire workloads remaining from the old cluster

After you have successfully migrated application workloads and devops components in the new OCP cluster, it's time to retire the old project set! Please shut down all running components from the old project set, make sure there is no persistent data remaining. Then you can head over to [Product Registry](https://registry.developer.gov.bc.ca/) and delete the project set from there!


### Related pages
- [Get started in the BC Gov Private Cloud PaaS](https://cloud.gov.bc.ca/private-cloud/our-services-in-private-cloud-paas/get-started-with-the-private-cloud-paas/)
- [Product Registry Service](https://registry.developer.gov.bc.ca/)
- [Different OCP hosting tires](https://cloud.gov.bc.ca/private-cloud/our-products-in-the-private-cloud-paas/silver-and-gold-tier-platforms/)
- [IDIR protected content](https://cloud.gov.bc.ca/private-cloud/idir-protected-content/)

**Comment by ShellyXueHan** [comment]
@caggles I'll be on flexday tomorrow, could you keep an eye on this ticket for Pilar and Sal in case they need input? Above is the draft pending review, feel free to modify it if you see fit! Once all good, Pilar can also help to add this content onto the wordpress site ;)

**Comment by Pilargit12** [comment]
Hi team, here is my revisioned version. 

📌 **Questions:** Can @caggles and/or @faisal-hamood tell me where the page should live on the website? 

📌 **Comments:** 
Please provide feedback on the substance of this text. 

- Are there any inaccuracies? 
- Are there any important points missing?
- Are there relevant details that should be included? 

As a subject matter expert, you are responsible for the quality of the information. As a Web UX Content Strategist, I am responsible for following style and accessibility guidelines so the information can be easily understood.

📌 **Text I did not change, as the current language is used in different parts of the website with different versions, perhaps due to typos**
- BC Gov Private Cloud PaaS remained the same rather than using the correct use of abbreviation: B.C. Government or Gov. 
- Example of another use: [BCGov]  (https://cloud.gov.bc.ca/private-cloud/our-products-in-the-private-cloud-paas/silver-and-gold-tier-platforms/)

--------------

# Migration between OCP clusters in the BC Gov Private Cloud PaaS

Is your team working on the OpenShift cluster? If you are looking to get onboarded, please visit [Get started in the BC Gov Private Cloud Paas](https://cloud.gov.bc.ca/private-cloud/our-services-in-private-cloud-paas/get-started-with-the-private-cloud-paas/).

Learn how to start the migration between different OCP clusters. If you have specific infrastructure needs that the current cluster can't fulfill, it's possible to move to another OpenShift hosting tier. 

Last updated: **May 19, 2023**

## On this page

* Migration requirements
* Step 1: Attend a migration assessment meeting
* Step 2: Set up your access to the new OpenShift cluster
* Step 3: Migrate applications
* Step 4: Retire workloads remaining from the old cluster
* Related pages

## Migration requirements
Before starting a migration, get familiar with the different [Openshift hosting tiers](https://cloud.gov.bc.ca/private-cloud/our-products-in-the-private-cloud-paas/silver-and-gold-tier-platforms/).

There are corresponding requirements per cluster for your team to meet before moving the application workload there. If you are clear and ready on which cluster you'd like to migrate to, follow the guide to Step 1. 

If you think it's necessary to migrate your application to a higher hosting tier but your team does not meet the requirements, please feel free to reach us out at [PlatformServicesTeam@gov.bc.ca](mailto:PlatformServicesTeam@gov.bc.ca) to provide you with further advice. 

## Step 1: Attend a migration assessment meeting

Request an assessment meeting to [PlatformServicesTeam@gov.bc.ca](mailto:PlatformServicesTeam@gov.bc.ca)

During the meeting with the Platform Services Team, you’ll get an overview of the different hosting tires from BC Gov Private Cloud PaaS, including what we do to support the platforms. 

Here are some of the main topics covered:

* The specific infrastructure needs from a different OCP cluster
* Which OCP cluster would be the best option
* An assessment on your team and application to determine if you are ready to move on towards a higher hosting tier 
* Migration timelines and followup actions
* Responsibilities as a product team working on a different cluster.

## Step 2: Set up your access to the new OpenShift cluster

Once the assessment meeting is completed and your team is ready, you can start a new project set request at [Product Registry](https://registry.developer.gov.bc.ca/).

Please make sure to include the following information in the request:

* The new project set name should match with the old one.
* Pick the OCP cluster previously discussed is the assessment meeting
* By default your new project set will start with a small quota set. 
* If you have successfully requested a quota increase in your current project set already, please mention this in the new quota request once the new project set is ready.  This will avoid going through another quota review meeting again.

Please note that Gold and GoldDR clusters share the same [authentication process](https://cloud.gov.bc.ca/private-cloud/our-services-in-private-cloud-paas/get-started-with-the-private-cloud-paas/#Step-2:-Set-up-your-accounts) as Silver. 

If you are migrating to Emerald, BCGOV VPN access is required. Find out more information about the [Emerald Cluster](https://cloud.gov.bc.ca/private-cloud/our-products-in-the-private-cloud-paas/silver-and-gold-tier-platforms/#emerald-hosting-tier).

## Step 3: Migrate applications

The migration path and requirements are different based on the type of cluster. The Platform Services Team provides the OCP platform infrastructure and the shared services, but you are responsible for updating the application to work on the new clusters.

For example, the Gold cluster comes with a Disaster Recovery cluster as GoldDR. The two clusters are geo-redundant, when a cluster wide incident happens on Gold, traffic to applications will be automatically redirected to GoldDR by the GSLB. However, you need to design the DR strategy for your application, and set them up so that your workloads can benefit from the cluster failover to achieve better service availability.

There are detailed documentation and how-to guides about working on different OCP clusters in the [IDIR protected content](https://cloud.gov.bc.ca/private-cloud/idir-protected-content/). You are highly encouraged to use the information to modify your application for the migration.

Make sure to also migrate your DevOps components, including but not limited to:

* CICD pipeline
* Database backup
* TLS cronjob 

To prevent any persistent data loss during the migration, please take a look at our [recovery guide](https://docs.developer.gov.bc.ca/recovery-responsibilities/) before starting!

## Step 4: Retire workloads remaining from the old cluster

After you have successfully migrated application workloads and DevOps components in the new OCP cluster, it's time to retire the old project set! 
1.  Please shut down all the running components from the old project set, make sure there is no persistent data remaining. 
2.  Head over to [Product Registry](https://registry.developer.gov.bc.ca/) and delete the old project set from there. 

## Related pages

* [Get started in the BC Gov Private Cloud PaaS](https://cloud.gov.bc.ca/private-cloud/our-services-in-private-cloud-paas/get-started-with-the-private-cloud-paas/)
* [Product Registry Service](https://registry.developer.gov.bc.ca/)
* [Different OCP hosting tires](https://cloud.gov.bc.ca/private-cloud/our-products-in-the-private-cloud-paas/silver-and-gold-tier-platforms/)
* [IDIR protected content](https://cloud.gov.bc.ca/private-cloud/idir-protected-content/)

**Comment by Pilargit12** [comment]
Wordpress page has been created - currently pending.  @Kolezhanchik will revise the format of the side links on the page so that they are the same as other pages.

**Comment by Pilargit12** [comment]
@ShellyXueHan @faisal-hamood 

The website is now live here: https://cloud.gov.bc.ca/private-cloud/our-products-in-the-private-cloud-paas/migration-between-ocp-clusters-in-the-bc-gov-private-cloud-paas/
