### ISSUE TITLE
Add Uptime.com monitoring for the EMERALD and KLAB2 clusters

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3938]
**Describe the issue**
During an incident we determined that neither KLAB2 or EMERALD clusters have entries for Uptime.com - need to create them and test that they work. This will also allow those clusters to be selected when there's a maintenance or outage event.

**How does this benefit the users of our platform?**
Provides better monitoring and ability to use the status pages to see the status of these clusters and provide updates linked to the specific clusters when events occur.

**Definition of done**

- [x] Uptime monitoring working for KLAB2 cluster
- [x] Uptime monitoring working for EMERALD cluster

**Comment by ShellyXueHan** [comment]
### Update:
- we can expose the cluster API endpoint for uptime.com to ping on, so as an alternative, we'll setup monitoring via Cerberus
- Cerberus has been installed on the nsx-t clusters already. But the route is using the cluster default which can't be accessed publicly either
- we'll need to request for a vanity domain for cerberus in Emerald and klab2

**Comment by wmhutchison** [comment]
Worked with Shelly to demonstrate the correct annotation for making Cerberus route be given a public IP address. 

Regarding "vanity domains" that means anything that's not the form of *.apps.<cluster>.devops.gov.bc.ca, does not necessarily mean some other type of domain we need to purchase. It seems that NNR still has control over the developer.gov.bc.ca domain, so we should be able to setup a DNS entry in NNR for the assigned IP address once it's determined for each cluster. Keep in mind that assigned IP addresses are not permanent, so if the involved routes are deleted/created again, DNS will likely need to be updated accordingly.

Last, since Cerberus is only returning a value of "true" or "false", it was agreed that Cerberus route can be changed to not require HTTPS, thus no longer needing to purchase an SSL cert for the FQDN/route. If this requirement changes in that Cerberus will share more than just a single value of true/false, then this will need to be revisited.

Once the final FQDN is decided for the new Cerberus route, my team needs to be notified since for domains/routes not involving *.apps.<cluster>.devops.gov.bc.ca, we need to get setup some back-end configs in AVI for that to work.

**Comment by ShellyXueHan** [comment]
Updates:
- updated cerberus routes with a vanity domain URL as `cerberus.<cluster>.developer.gov.bc.ca`
- updated uptime.com monitor to check on the new URLs

**Comment by wmhutchison** [comment]
@ShellyXueHan CCM in EMERALD was pushed today which created your vanity URL for cerberus. Just need to add DNS entry for the assigned IP and thus conclude this work. :)

**Comment by ShellyXueHan** [comment]
Already added, uptime.com also monitoring the new URL now! I manually created the route in nsx-t clusters last week, looks like gitops has no problem syncing. all good, thank you William!

**Comment by ShellyXueHan** [comment]
### Update:
Will keep an eye on how it goes with cerberus monitoring as it's more sensitive than OCP default API health endpoint. So let's wait for two/three weeks and see how we like it before putting it up on uptime.com

**Comment by ShellyXueHan** [comment]
### Updates:
Whenever there are node draining from klab2 or emerald, the cerberus health endpoint will turn false. While this is not something that will impact apps on the cluster, which thus shouldn't count towards a downtime. We might need to consider either configuring the cerberus instance with fewer checks or go with something else.

@w8896699 I'll pass the follow up task to you to continue working on nsx-t cluster monitoring options!

**Comment by ShellyXueHan** [comment]
#4028
