### ISSUE TITLE
Install Data Science in Silver

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3993]
**Describe the issue**
Data Science is installed in KLAB, but there's not enough CPU there to really test it out. So lets install it in Silver where we have some more capacity.

**What is the Value/Impact?**
Test out the Data Science operator and determine if its worth purchasing

**What is the plan? How will this get completed?**
Install ODS in Silver
Apply custom hacks needed to get the false alerts to stop
Apply quota to ods notebook namespace to prevent over-use
Add annotations to test users tools and dev namespaces to allow them to leverage ODS

**Identify any dependencies**
None

**Definition of done**
ODS installed in Silver and enabled for testing
Testers emailed with details

**Comment by StevenBarre** [comment]
ODS installed in Silver

Label changes from https://access.redhat.com/solutions/7002893 applied

`redhat-ods-applications` got quotas automatically from the default template in Silver. Adjusted up the compute long running quota.

| Resource | Used | Hard |
|---|---|---|
| limits.cpu | 16800m | 32 |
| limits.memory | 45Gi | 128Gi |
| pods | 15 | 100 |
| requests.cpu | 6390m | 32 |
| requests.memory | 11552Mi | 128Gi |

`redhat-ods-monitoring` got quotas automatically from the default template in Silver.

| Resource | Used | Hard |
|---|---|---|
| limits.cpu | 16800m | 32 |
| limits.memory | 45Gi | 128Gi |
| pods | 15 | 100 |
| requests.cpu | 6390m | 32 |
| requests.memory | 11552Mi | 128Gi |

`redhat-ods-operator` has no quota, but is just running the one operator pod.

`rhods-notebooks` got quotas automatically from the default template in Silver. Increased to a high but sane value.

| Resource | Used | Hard |
|---|---|---|
| limits.cpu | 16800m | 32 |
| limits.memory | 45Gi | 128Gi |
| pods | 15 | 100 |
| requests.cpu | 6390m | 32 |
| requests.memory | 11552Mi | 128Gi |

**Comment by StevenBarre** [comment]
Added 4 users by IDIR to the group `oc adm groups add-users rhods-admins <user>` and then emailed them all telling them of the new install. Will wait for feedback on which namespaces they want annotated.

**Comment by wmhutchison** [comment]
As learned when manually installing in SILVER, we trigger PrometheusOperatorRejectedResources event because the openshift-user-workload-monitoring namespace stack wants to be able to reach the monitors based out of the redhat-ods-applications namespace per this log snippet taken from the user prometheus operator.

level=warn ts=2023-06-16T19:00:43.006227538Z caller=operator.go:2255 component=prometheusoperator msg="skipping servicemonitor" error="it accesses file system via bearer token file which Prometheus specification prohibits" servicemonitor=redhat-ods-applications/odh-model-controller-metrics-monitor namespace=openshift-user-workload-monitoring prometheus=user-workload

Thus following https://access.redhat.com/solutions/6706741 we resolve via ths:

```
oc label namespace redhat-ods-applications openshift.io/cluster-monitoring=true
```

Not to be confused with https://access.redhat.com/solutions/7002893 which documents specific label adjustments for a different ODS namespace for another AlertManager notification type.

**Comment by StevenBarre** [comment]
Pods in `redhat-ods-monitoring` were crashing due to OOM. The default LimitRange was setting a low mem limit on the prometheus container. Removed the quotas and limits to allow it to run properly.

Sent a follow up email to the test users as I'd not heard from anyone yet.

**Comment by StevenBarre** [comment]
Provided Brad some docs on the available Notebook images https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science_self-managed/1.28/html/getting_started_with_red_hat_openshift_data_science_self-managed/creating-a-project-workbench_get-started#options-for-notebook-server-environments_get-started

and some docs on how to install additional libraries into Jupyter https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science_self-managed/1.28/html/working_on_data_science_projects/working-on-data-science-projects_nb-server#installing-python-packages-on-your-notebook-server_nb-server

**Comment by StevenBarre** [comment]
Brad confirms its working, so closing this issue. Will open another if more work is needed.
