### ISSUE TITLE
Weekly CCM PROD Push for June 20th to June 22nd

### ISSUE THREAD

**Issue by tmorik** [BCDevOps/developer-experience#3994]
**Describe the issue**
This ticket will track efforts spent toward creating the next CCM release and promoting it against the three production Openshift clusters.

**Definition of done**
- [x] Create suitable GitHub Release before EOD Friday
- [x] Create suitable Standard Change RFCs and assign to team members as appropriate
- [x] Create and Receive approval for PR incrementing CCM version for PROD clusters
- [x] Ensure version increment PR is merged before executing any RFCs
- [x] Execute RFC for SILVER & EMERALD cluster
- [x] Execute RFC for GOLD cluster
- [x] Execute RFC for GOLDDR cluster

**Comment by tmorik** [comment]
```
Weekly CCM relase v4.16.2

## What's Changed
* KEDA - Fixes to KEDA Operator for GA version by @wmhutchison https://github.com/bcgov-c/platform-gitops-gen/pull/672

```

**Comment by wmhutchison** [comment]
Posting my instructions as taken from the KEDA ZenHub ticket, since all regular Openshift PROD clusters will need to follow specific instructions before allowing a PR merge to proceed.

The following steps were documented during handling of CLAB regarding resolving KEDA issues. Barring minor tweaks, these should also work against all PROD clusters.

1. In GitOps web console, pause both "cluster-apps" and "keda" apps.

2. Remove kedacontroller.
  ```
  oc -n openshift-keda delete kedacontroller keda
  ```

3. Remove Keda subscription.
  ```
  oc -n openshift-keda delete subs openshift-custom-metrics-autoscaler-operator
  ```

4. Remove CSV's. Check namespace first and adjust specifics below if not an exact match.
  ```
  oc -n openshift-keda get csv | grep custom-metrics-autoscaler
  oc -n openshift-keda delete csv custom-metrics-autoscaler.v2.8.2-174 custom-metrics-autoscaler.v2.10.1-253
  ```

5. Remove CRD's. Double-check to make sure all CRD's matching "keda" are gone.
  ```
  oc get crd | grep keda
  oc delete crd clustertriggerauthentications.keda.sh kedacontrollers.keda.sh scaledjobs.keda.sh scaledobjects.keda.sh triggerauthentications.keda.sh
  ```

6. Delete KEDA clusterroles if they still exist. 
  ```
  oc get clusterrole | grep keda
  oc delete clusterrole keda-external-metrics-reader keda-operator keda-operator-admin keda-operator-edit keda-operator-view
  ```

7. Delete KEDA clusterrolebinding if they still exist.
  ```
  oc get clusterrolebinding | grep keda
  oc delete clusterrolebinding keda-hpa-controller-external-metrics keda-operator keda-system-auth-delegator 
  ```

8. Delete KEDA project. If stuck, grep apiservice and if still present, nuke any matching hits for "keda".
  ```
  oc get apiservice | grep keda
  oc delete project openshift-keda
  ```

9. Delete the Cluster Metric Autoscaler Operator.
  ```
  oc delete operator/openshift-custom-metrics-autoscaler-operator.openshift-keda
  ```

10. Merge cluster's CCM repo PR.

11. Confirm the PR number shows up in GitOps web console, and then unpause "cluster-apps".

12. Monitor state of KEDA operator in cluster's web console. Confirm with state of CCM.
