### ISSUE TITLE
Vault testing suite monitoring with N8N

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4008]
**Describe the issue**
Doesn't look like there is monitoring setup on the vault testing suite as I don't see alerts when things are broken there. Monitoring on vault server status is not good enough. We will need to also check if app pods can pull secrets from Vault via the injector.

Here are more information about the testing suite: https://github.com/bcgov-c/tenant-gitops-ea8776

**Definition of done**
- [ ] implement n8n check if not yet exist
- [ ] or fix the checks if exist but not working

**Comment by w8896699** [comment]
We don't use n8n to do day-to-day regular monitoring, we use sysdig for this purpose. 
Sysdig did capture the outage, but because it was too noisy, I let it shut up for any outage that is less than 2 hours....And that why you don't have any notification.

Question, if vault test is not able to pull secrets, will the pod status shows healthy?

**Comment by ShellyXueHan** [comment]
oh right i kept thinking N8N will be the all time running thing. So the test deployment will go down, but patroni won't. they each reflect a different use case:
- patroni sts only use the vault init container, so if vault is down, the DB pod won't be affected till restart
- test deployment use both vault init and sidecar container, which will reflect the issue when vault is down

If you have sysdig setup for that, we are all good then! Please also tag me in the notification message ;)
