### ISSUE TITLE
Review OCP 4.13 Release Notes - Tatsuya

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#4075]
**Describe the issue**
Review the [OCP 4.13 Release Notes](https://docs.openshift.com/container-platform/4.13/release_notes/ocp-4-13-release-notes.html) for any changes that will impact the product teams, ops team, or platform services team. Also look for any exciting new features that community should know about.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Read the release notes. Add any bits you find interesting and needing of discussion as comments here.

**Identify any dependencies**
None

**Definition of done**
- [ ] Fully read the release notes and added anything of interest as a comment here.

**Comment by tmorik** [comment]
>Toolbox is deprecated in RHCOS
The toolbox script is deprecated and support will be removed from a future OpenShift Container Platform release.

`toolbox` is used our SOS report for node steps. 

- https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Debugging.md#generate-sos-report-for-node

 
> Kubernetes topology labels
Two commonly used Kubernetes topology labels are being replaced. The failure-domain.beta.kubernetes.io/zone label is replaced with topology.kubernetes.io/zone. The failure-domain.beta.kubernetes.io/region label is replaced with topology.kubernetes.io/region. The replacement labels are available starting with Kubernetes 1.17 and OpenShift Container Platform version 4.4.

Maybe This could affect the Argo? 

- https://github.com/search?q=repo%3Abcgov-c%2Fplatform-gitops-gen%20failure-domain.beta.kubernetes.io&type=code

>Beta APIs removed from Kubernetes 1.26
Kubernetes 1.26 removed the following deprecated APIs, so you must migrate manifests and API clients to use the appropriate API version. For more information about migrating removed APIs, see the Kubernetes documentation.

![image.png](https://images.zenhubusercontent.com/5ea9f983189dd56ef6dde075/0d7b9847-964a-4b44-a4c8-7c1c83c7519d)

Minor, but `autoscaling/v2beta2` needs to be updated with `autoscaling/v2` for Argo deployment, I think:

- https://github.com/search?q=repo%3Abcgov-c%2Fplatform-gitops-gen%20autoscaling%2Fv2beta2&type=code

> New flag added to run must-gather in a specified namespace
With OpenShift Container Platform 4.13, the --run-namespace flag is now available for the oc adm must-gather command. You can use this flag to specify an existing namespace to run the must-gather tool in.

>For more information, see About the must-gather tool.

maybe useful?

>CoreDNS updated to 1.10.1
OpenShift Container Platform 4.13 updates CoreDNS to 1.10.1. CoreDNS now uses the DNSSEC DO Bit that was specified on the originating client query. This reduces the DNS response UDP packet size when a client is not requesting DNSSEC. Consequently, the smaller packet size reduces both the chance of DNS truncation decreasing by TCP connection retries and overall DNS bandwidth.

Hope this won't be cause of any issue like we got a bit while ago. (e.g DNS issue for MCS clusters - PRB0040825, CoreDNSErrorsHigh - RH Case 03104975 etc.. )

>Updated web console behavior when disabling copied CSVs
The OpenShift Container Platform web console has been updated to provide better Operator discovery when copied cluster service versions (CSVs) are disabled on a cluster.

>When copied CSVs are disabled by a cluster administrator, the web console is modified to show copied CSVs from the openshift namespace in every namespace for regular users, even though the CSVs are not actually copied to every namespace. This allows regular users to still be able to view the details of these Operators in their namespaces and create custom resources (CRs) brought in by globally installed Operators.

>For more information, see Disabling copied CSVs.

ZH task : https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/3006

>Support for setting the core user password
You can now create a password for the RHCOS core user. If you cannot use SSH or the oc debug node command to access a node, this password allows you to use the core user to access the node through a cloud provider serial console or a bare metal baseboard controller manager (BMC).

>For more information, see Changing the core user password for node access.

No need for us, I guess. but good to know.

>Pod disruption budget (PDB) unhealthy pod eviction policy (Technology Preview)
With this release, specifying an unhealthy pod eviction policy for pod disruption budgets (PDBs) is available as a Technology Preview feature. This can help evict malfunctioning applications during a node drain.

TP, but nice.

>Support for graceful node shutdown
A graceful node shutdown delays the eviction of pods during a node shutdown. In OpenShift Container Platform 4.13, you can configure the kubelet to enable a graceful node shutdown so that pods running critical workloads are not interrupted.

To configure graceful node shutdowns, you can specify a termination grace period for regular and critical pods in the KubeletConfig custom resource. A termination grace period defines a time period for the pod to complete any ongoing tasks before terminating. You can also add priority classes to pods to specify the order of termination.

>For further information see Managing graceful node shutdown.

Interesting, I think.
