### ISSUE TITLE
Kyverno improvements investigation

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#4162]
**Describe the issue**
Kyverno is a useful tool, but there can be a lot of problems if it is not stable.  Investigate strategies for mitigating the risk of a Kyverno service failure.

**What is the Value/Impact?**
Because of its central role in the cluster, a broken Kyverno will affect many applications and cause downtime.  We need to minimize disruptions in the production clusters.

**What is the plan? How will this get completed?**
- [x] Ensure that the Kyverno Deployment has sufficient resources in all clusters
- [x] Configure Kyverno to minimize potential outages
- [x] Review ClusterPolicies to identify those that should be reconfigured for a more focused purpose and those that might need to be removed
- [x] Check with Gerald Nunn to see if he has any pointers for us (Red Hat DevOps specialist)

**Identify any dependencies**
* CCM

**Definition of done**
- [x] Testing is completed in a lab cluster
- [x] CCM PR is prepared

**Comment by StevenBarre** [comment]
Had a call/debug session and worked through deleting different webhooks to see which one caused the errors we'd seen before. Narrowed this down to the `kyverno-resource-validating-webhook-cfg` validating webhook. It is set to a `failPolicy` of `Fail` instead of `Ignore`.

Some more testing and digging in API audit logs shows that the `leaderelection.go` errors we see come from code that is using ConfigMaps to do leader election, in operator and in things like Patroni. This is different from what I believed about it affecting `Leases`.

In addition to the above recommendations from Ian, we should also update all the ClusterPolicy objects to use `failPolicy: Ignore` so that a failing Kyverno does not block updates to `ConfigMaps` in tenant namespaces.

**Comment by IanKWatts** [comment]
The webhook configuration contains two admissionReviewVersions, one for Ignore and one for Fail.  These are determined by the ClusterPolicies.  Changing a ClusterPolicy from Fail to Ignore will cause that rule to be moved to the 'Ignore' admissionReviewVersion, but then Kyverno will also no longer enforce that rule.  I don't think we can both avoid errors when the service has failed AND enforce the rule when the service is working.

**Comment by IanKWatts** [comment]
**Correction:** We can set the ClusterPolicies to 'Ignore' and they are still enforced.  So that's good!  Should do one more kyverno failure test to make sure that it will in fact ignore the failure and not break leader elections that use ConfigMaps.

**Comment by IanKWatts** [comment]
P.S., thanks to Steven for his help in digging into this issue!

**Comment by IanKWatts** [comment]
CCM PRs are created and on hold until the wildfire emergency is over:

* Upgrade Kyverno to 1.9 in all lab clusters
https://github.com/bcgov-c/platform-gitops-gen/pull/710 

* Set ClusterPolicy failurePolicy to Ignore
https://github.com/bcgov-c/platform-gitops-gen/pull/715
