### ISSUE TITLE
OCP 4.13 Meeting to discuss Release Notes

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4435]
**Describe the issue**
Once everyone has had a chance to review the [OCP 4.13 Release Notes](https://docs.openshift.com/container-platform/4.13/release_notes/ocp-4-13-release-notes.html) for any changes that will impact the product teams, ops team, or platform services team, have a meeting to discuss each persons individual findings/notes.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
AdvSol to schedule a MS Teams meeting to have everyone discuss.

**Identify any dependencies**
See blockers

**Definition of done**
- [ ] Meeting held

**Comment by IanKWatts** [comment]
To check:
* Operator SDK 1.25 --> 1.28; projects created with the SDK should be compatible with 1.2.8 or updated; might need to test our custom operators after lab upgrade
* By any chance has the DXC team put SSH keys on the nodes in /home/core/.ssh/authorized_keys?  These now go in /home/core/.ssh/authorized_keys.d/ignition
* Wildcard DNS entries under cluster.local are deprecated: not used?
* HPA: change 'autoscaling/v2beta2' --> 'autoscaling/v2'; bcgov-c/platform-gitops-gen/playbooks/argocd/operator-uninstall.yaml & bcgov-c/advsol-docs/OCP4/AutoscalingDemo.md, for example

Of interest:
* In Developer Perspective, create a serverless function by using the Import from Git flow - and other enhancements
* Pod disruption budget (PDB) unhealthy pod eviction policy (Technology Preview); Requires 'TechPreviewNoUpgrade', which cannot be undone and prevents minor version updates
* In a future release, pods with security violations will be rejected instead of just issuing a warning
* Bugfix in Pipeline builder and YAML view; might be something our users have seen?

**Comment by StevenBarre** [comment]
Should let people know they can log in to cli with a [web browser](https://docs.openshift.com/container-platform/4.13/cli_reference/openshift_cli/getting-started-cli.html#cli-logging-in-web_cli-developer-commands) now

Need a ticket to set the [core user password](https://docs.openshift.com/container-platform/4.13/post_installation_configuration/machine-configuration-tasks.html#core-user-password_post-install-machine-configuration-tasks) so we can access nodes via console if SSH is down.

**Comment by wmhutchison** [comment]
All of the front-facing items I've noted have already been noted here. Internally looking forward to this feature in SILVER.

https://docs.openshift.com/container-platform/4.13/release_notes/ocp-4-13-release-notes.html#ocp-4-13-lsof-rhcos

* lsof now part of RHCOS. Will have to see it in practice to see how good/useful it'll be for troubleshooting.

**Comment by IanKWatts** [comment]
I've checked these custom operators in KLAB and CLAB, where we're already running 4.13.  No issues.
- benny operator
- porter operator
- warden operator

**Comment by tbaker1313** [comment]
Meeting scheduled.

**Comment by tbaker1313** [comment]
Changes that impact Developers:
- Enhancements to Developer perspective (creating serverless functions, pipeline as code configuration in gui, view pod traffic, customize web terminal)
- Enhancements to networking metrics
- Web console behaviour changed with disabling copied CSVs
- API deprecations but only really one that's relevant to users HorizontalPodAutoscaler from autoscaling/v2beta2 to autoscaling/v2
- Operator SDK is going to be deprecated soon
- Pod security violations are still unenforced but eventually will be.
- Wildcard DNS entries under cluster.local are deprecated

**Comment by tbaker1313** [comment]
Completed.
