### ISSUE TITLE
INC0035046 Metrics pods failing

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#450]
Over the weekend the Metrics pods crashlooped a bunch and woke up on-call. This is related to the ongoing RH case https://access.redhat.com/support/cases/#/case/02635853

**Comment by sbarre-esit** [comment]
RH suggested Cassandra was having issues with its disk access. Looked into graphs from NetApp and vCenter and saw some significant IO latency. Emailed Storage team for assistance.

**Comment by wmhutchison** [comment]
Due to ongoing stability issues with INFRA nodes due to the use of NetAPP block storage (which is what Cassandra pod was using), an emergency swap of storage was made to have Cassandra go back to using Gluster block storage.

This migration has resulted both in an improvement in stability of metrics pods no longer crashing and/or internal metrics monitoring kicking off, as well as taking a significant I/O load off the NetApp appliances.

The "next steps" is to focus priority on resolving overall stability issues with NetApp block storage, and when done, we can tender a migration back to said storage for Cassandra, since long-term that is the future solution. If there are issues with performance at that time, it can be revisited, but for now, stability is the top priority both for Metrics services and the INFRA nodes in general.

**Comment by sbarre-esit** [comment]
Performed some DB cleanups in Cassandra and metrics seem to be much happier now.
