### ISSUE TITLE
Prepare plan for moving nonprod Vault secrets to Lab instance

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#4572]
**Describe the issue**
The cost of our Vault license depends on the number of users in the Production instance.  By moving nonprod secrets from the Prod instance to the Lab instance, we can significantly reduce the number of users that count towards our license.  Prepare a plan for this change.

**What is the Value/Impact?**
This could save a lot of money.

**What is the plan? How will this get completed?**
Make a list of all the things that would have to change in order to make this move and update existing automation.
Identify documentation that would have to be updated.
Determine the impact to the community and ensure that change is practical.
Prepare a plan for the actual migration.
Test the migration with some select projects.

**Identify any dependencies**
* Provisioner `app-provisioner` image, which includes automation for Vault access configuration

**Definition of done**
- [ ] Migration plan is prepared
- [ ] Impact to community is clearly defined
- [ ] Migration is tested

**Comment by lukegonis** [comment]
Closing this issue due to:
- it would be a lot of work
- would require teams to reconfig their apps
- would create a disconnect between prod and non prod environments
- not currently necessary due to us not yet hitting our user limit
- awaiting updates from SecOps team
 
Once charge back is in place we will reconsider
