### ISSUE TITLE
OCP 4.13 Upgrade Openshift in CLAB and KLAB

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#4604]
**Describe the issue**
Run the OCP 4.13 upgrade in the labs to mitigate a runc vulnerability.

**BLOCKED BY**
TBD

**Additional context**
https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Upgrade.md

**Definition of done**
- [x] CLAB upgraded to OCP 4.13.32
- [x] KLAB upgraded to OCP 4.13.32
- [x] MachineConfig changes applied
- [x] CCM applied
- [x] EnCase updated
- [x] ETCD Backup updated
- [x] Nagios updated
- [x] Pruner updated
- [x] vROps updated
- [x] Logging updated
- [x] Sample Operator updated

**Comment by wmhutchison** [comment]
Tim confirmed OCP 4.13.32 to have dropped today, which is the release for OCP 4.13 that we were waiting on for the runc fix. Kicking off CLAB upgrade right away, followed by KLAB after.

**Comment by wmhutchison** [comment]
Upgraded CLAB to the required new version. Also upgraded operators other than RH Integration including Logging. Will check in the morning to make sure services ran via cron (etcd backup, pruning) ran without issue and that the other components do not have busted pods. Merged CLAB CCM as well to see if that breaks anything.

Looking good though thus far, should be fine to pull the trigger on KLAB in the morning.

**Comment by wmhutchison** [comment]
CLAB's stackrox collector pods went into crashloop after CLAB was upgraded today. Might be a case of pulling the CLAB trigger too close to LAB ACS maintenance since ACS has to have/install supported kernel components, so freshly upgraded CLAB might have had to wait for that to drop. Either way, bouncing the affected collector pods seems to have fixed it, but will double-check in the morning to make sure.

**Comment by wmhutchison** [comment]
Closing this off, no detectable issues noted for KLAB/CLAB post upgrade.
