### ISSUE TITLE
OCP NSX 4.14 Review Release Notes - William

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4796]
**Describe the issue**
Review the [OCP 4.14 Release Notes](https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html) for any changes that will impact the product teams, ops team, or platform services team. Also look for any exciting new features that community should know about.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Read the release notes. Add any bits you find interesting and needing of discussion as comments here.

**Identify any dependencies**
None

**Definition of done**
- [x] Fully read the release notes and added anything of interest as a comment here

**Comment by wmhutchison** [comment]
Starting on this now.

**Comment by wmhutchison** [comment]
"RHEL 6 base image containers are not supported on RHCOS container hosts but are supported on RHEL 8 worker nodes.". A similar note exists for OCP 4.13 since RHCOS is technically RHEL9, so of note, but anyone whose images broke because of this have already taken action by now (hopefully). If we pass this info onto the community, keep this fact in mind that this is not a net-new change, but one already in play.

**Comment by wmhutchison** [comment]
https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html#ocp-4-14-vsphere-pre-existing-template - will need to investigate this further to see if it affects how we (re)build our NSX-enabled Openshift nodes, or if older/existing docs still work and are fine.

**Comment by wmhutchison** [comment]
https://docs.openshift.com/container-platform/4.14/operators/admin/olm-adding-operators-to-cluster.html#olm-installing-specific-version-web-console_olm-adding-operators-to-a-cluster - this will not affect how we now manage Operator versioning in CCM, it will better align Proof of Concept work to match since installing an operator via web console will also allow specific versioning selection, thus allowing better transition from Proof of Concept to managed-by-CCM.

**Comment by wmhutchison** [comment]
https://docs.openshift.com/container-platform/4.14/applications/creating_applications/creating-applications-using-cli.html#setting-the-import-mode - hmm. Will this align more with allowing users to ensure their DB pods in a Patroni cluster are put onto nodes which do not share the same ESXi host?

**Comment by wmhutchison** [comment]
https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html#ocp-4-14-monitoring-changes-to-alerting-rules - YAY for MultipleContainersOOMKilled being removed, one less piece of spam to deal with.

**Comment by wmhutchison** [comment]
https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html#ocp-4-14-notable-technical-changes - "Future restricted enforcement for pod security admission". Could be mistaken, but the biggest take-away for platform admins is following up on the occasional AlertManager notice commonly seen after a CCM sync action, since it's almost certainly a function of us having created an "openshift-" namespace and need to to ensure admission labels are being correctly setup to sync via an appropriate label on the namespace in question.
