### ISSUE TITLE
OCP NSX 4.14 Review Release Notes - Ian

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4802]
**Describe the issue**
Review the [OCP 4.14 Release Notes](https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html) for any changes that will impact the product teams, ops team, or platform services team. Also look for any exciting new features that community should know about.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Read the release notes. Add any bits you find interesting and needing of discussion as comments here.

**Identify any dependencies**
None

**Definition of done**
- [x] Fully read the release notes and added anything of interest as a comment here

**Comment by IanKWatts** [comment]
RHEL 6 base image containers are not supported on RHCOS container hosts but are supported on RHEL 8 worker nodes. For more information, see the Red Hat Container Compatibility matrix.

API storage.k8s.io/v1beta1 is now storage.k8s.io/v1

'oc login --web' to log in with browser instead of token

PDBs now support 'unhealthyPodEvictionPolicy: AlwaysAllow'
    to allow crashing pods to be evicted
    default is 'IfHealthyBudget'

CronJob time zone setting is now GA
    .spec.timeZone

Future restricted enforcement for pod security admission
    Is there a way users can check their existing deployments?

DeploymentConfig resources are now deprecated
    Will support for DCs go away in the future?
    Should we tell users to plan to migrate to Deployments?

CoreDNS now supports a 'protocolStrategy' field
    Set it to 'TCP' to avoid UDP responses that could be larger than the buffer size of 512 bytes
