### ISSUE TITLE
OCP NSX 4.14 Meeting to discuss Release Notes

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4803]
**Describe the issue**
Once everyone has had a chance to review the [OCP 4.14 Release Notes](https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html) for any changes that will impact the product teams, ops team, or platform services team, have a meeting to discuss each persons individual findings/notes.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
AdvSol to schedule a MS Teams meeting to have everyone discuss.

**Identify any dependencies**
See blockers

**Definition of done**
- [ ] Meeting held

**Comment by wmhutchison** [comment]
Aiming to have a meeting for this the week of June 10th (likely on June 12th), pending tweaks depending on schedules. The aim is to have this discussion but not worry about community comms until we delve into the same upgrade for regular Openshift which we hope will start later this June.

**Comment by wmhutchison** [comment]
Moving into Backlog. I'll take the opportunity to go everyone's completed tickets but not schedule a meeting until we're closer to the reality of doing an OCP 4.14 upgrade in regular Openshift, so that everything can be refreshed in peoples' minds when it comes to doing the community comms.

**Comment by wmhutchison** [comment]
Due to the relatively small audience for the involved PROD cluster (EMERALD), I will take all supplied notes and collate them as per normal, but there will be no meeting or additional comms for this, as it may confuse too many folks who are not yet using EMERALD. Instead, such notes will feed into this same exercise when we do the upgrade for the main Openshift clusters.
