### ISSUE TITLE
OCP NSX 4.14 Test full node rebuild in KLAB2

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4834]
After upgrading KLAB2 perform a node rebuild to ensure everything is working as expected.
Instructions are at https://github.com/bcgov-c/rhcos-ignition-builder

Definition of done:
- [ ] ~~One KLAB2 node is successfully rebuilt~~

**Comment by wmhutchison** [comment]
Will discuss with Steven along with Dan when Steven's back in the office. This item has not been done in KLAB2/EMERALD to date due to historical issues encountered in the very early days of KLAB2/NSX due to cluster build issues that were possibly tied to NSX not fully cleaning up metadata properly when removing nodes/cluster and rebuilding.

This does need to be revisited and properly done, but not sure if tying it to the OCP 4.14 series is appropriate or not, since not sure how much time will be required to see this through, etc. 

At the very least, it'd be good to put in a ticket (if Dan wants one) to get VMWare to refresh their VM template that's used to build new nodes, since it's still likely sitting at OCP 4.8, and if we needed to rebuild anything in a hurry, would be a blocker if not available.

**Comment by wmhutchison** [comment]
Closing this off as unexecuted. We have yet to do a node rebuild in KLAB2/EMERALD. Such will happen in the future as time permits, but not within the structure of an Openshift 4.14 upgrade.
