### ISSUE TITLE
PO friendly email for resources waste

### ISSUE THREAD

**Issue by w8896699** [BCDevOps/developer-experience#4966]
Billy was approached by Jennifer Dowd to created a PO friendly email to communicate once per quarter. This report contains 10 offenders using the platform product registry contacts. 

What needs to be clarified 

- [x] Example of the report that needs a PO friendly version of the content 
- [x] Explanation of what Billy communicates through that report and why should a PO care about it
- [x] What is the purpose of the report? 
- [x] What are the action items for the PO to complete? (need to know, need to do) 

Action items to tackle this: 

- [x] Pilar and Billy meet where he shares the report as an example and questions above are discussed 
- [x] Billy creates a draft based on those discoveries 
- [x] Pilar will review draft,  edit and style the message for a template for an email 
- [x] Billy will share draft with Jennifer 
- [x] If any edits, Pilar can make the changes (if any)  and once approved it can be distributed along with the report

**Comment by Pilargit12** [comment]
Hi @w8896699 suggested draft below and [Word](https://bcgov-my.sharepoint.com/:w:/g/personal/pilar_solaresvelasco_gov_bc_ca/EdvQumhZvWlNhv1LFfictp8BTs4j3FSHKvo27p6f_zOmBA?e=khpcRt) doc to share with Jennifer Dowd.


**Subject: Action required: Top 10 CPU resource offenders**

 
Hi [Product Owner], 

We have identified the top 10 offenders for CPU wastage in our shared environment. Below is a summary of the key data: 

**Top 10 CPU Wastage** 
``` 
63.98 21001b-dev 0.1264875645456464654 64 
##.## #####-dev #.################### ## 
##.## #####-dev #.################### ## 
##.## #####-dev #.################### ## 
##.## #####-dev #.################### ## 
##.## #####-dev #.################### ## 
##.## #####-dev #.################### ## 
##.## #####-dev #.################### ## 
##.## #####-dev #.################### ## 
##.## #####-dev #.################### ## 
``` 
  
**Format example** 
CPU Core Wasted | Namespace | CPU Core in use | CPU booked 
63.98           | 12345-dev | 0.1237867687678689 | 64 


1. **CPU Core wasted:** This represents the amount of CPU resources that are allocated but not effectively utilized. It's essentially the unused capacity that could otherwise be available for other processes or teams

2. **Namespace:** In a Kubernetes environment, a namespace is a way to divide cluster resources between multiple users. It helps to organize and manage resources in a shared cluster, essentially acting as a virtual cluster

3. **CPU Core in use:** This is the actual CPU core usage by a specific process or application. It shows how much CPU power is being actively consumed that particular namespace or workload

4. **CPU Booked:** This indicates the total amount of CPU resources that have been reserved for a particular namespace or application. These resources are set aside and are not available for use by other teams or processes, even if they are not being fully utilized


**Why this matters** 
- Overused CPU cores prevent other teams from utilizing shared resources 
- Reducing CPU wastage will improve overall system performance 
  
**Actions required** 

1. Contact your technical lead and team to review the wasted resources 
2. Instruct your developers to optimize the resource usage 

Please refer your team to these guides for more details: 

- [Application resource tuning](https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/automation-and-resiliency/application-resource-tuning/) 

- [Managing resource quotas in Kubernetes: A complete guide](https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/app-monitoring/managing-resource-quotas-in-kubernetes/) 

 Thank you for your immediate attention to this matter. If you have any questions regarding this report, please contact us at PlatformServicesTeam@gov.bc.ca  

  

Best regards, 

  
Platform Services Team

**Comment by Pilargit12** [comment]
2nd Review after feedback: 

Subject: Action required: Top 10 CPU processes contributing to CPU wastage 

Hi [Product Owner],  

We are reaching out to bring to your attention some important findings regarding CPU resource usage within our shared environment. Efficient utilization of platform resources is critical to maintaining optimal performance and ensuring fair access for all teams.  

Below is a summary of the key data we have identified:  

 
Project: XXXXXX 
CPU Core wasted: XX 
CPU Core in use: XX 
CPU Booked/Occupied: XX 
 

**Breakdown of key data**  

1. **CPU Core wasted**: This represents the amount of CPU resources that are allocated but not effectively utilized. It's essentially the unused capacity that could otherwise be available for other processes or teams 

2. **CPU Core in use**: This is the actual CPU core usage by a specific process or application. It shows how much CPU power is being actively consumed by a namespace or workload 

3. **CPU Booked**: This indicates the total amount of CPU resources that have been reserved for a particular namespace or application. These resources are set aside and are not available for use by other teams or processes, even if they are not being fully utilized 
 

**Why this matters** 

As outlined in the Memorandum of Understanding (MoU), it is our collective responsibility to ensure that applications use platform resources efficiently, including CPU, RAM, and storage. The OpenShift Platform environment operates on shared resources available to all teams.  

If we continue to overuse CPU cores it’ll continue to prevent other teams from utilizing these shared resources, leading to inefficiencies and potential performance degradation for everyone along with:  

* Increased operational costs: Wasted CPU resources contribute to higher operational costs. Even if the resources aren't actively used, maintaining them incurs costs for power, cooling, and data center space. Efficient usage can lead to significant cost savings 
 
* Reduced system stability: Overallocation of CPU can lead to resource contention among applications. This might not only affect the performance of the over-allocating application but can also lead to stability issues across the entire platform, potentially affecting multiple teams 
 
* Delayed scaling operations: When CPU resources are tied up unnecessarily, scaling operations for other applications that actually need these resources to handle increased load can be delayed. This can affect the agility of the business to respond to demand spikes 
 
* Inefficiency in resource allocation: Continuous overallocation of resources leads to a culture of inefficiency where resources are not being utilized thoughtfully. This can slow down the overall innovation on the platform as fewer resources are available for experimenting with new solutions 
 
* Environmental impact: Data centers consume a large amount of energy. By optimizing resource usage, the overall energy consumption of the data center can be reduced, which contributes to environmental sustainability efforts. 

**Actions required** 

1. **Review and plan**: Contact your technical lead and development team to review the wasted resources and develop a plan to adjust your usage, including an estimate of the associated cost 

2. **Optimize usage**: Instruct your development team to optimize resource usage to ensure efficient allocation of platform resources 

Please refer your team to these guides for more help:  

- [Application resource tuning](https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/automation-and-resiliency/application-resource-tuning/)  

- [Managing resource quotas in Kubernetes: A complete guide](https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/app-monitoring/managing-resource-quotas-in-kubernetes/)  

By reducing CPU wastage, we can improve overall system performance, enhancing the speed and reliability of solutions across the board. 

Thank you for your immediate attention to this matter. If you have any questions regarding this report, please contact us at PlatformServicesTeam@gov.bc.ca   

Best regards,  
Platform Services Team

**Comment by Pilargit12** [comment]
**3rd Draft**

**Subject: Action required: Top 10 CPU projects contributing to CPU wastage**   

Hi [Product Owner], 

We are reaching out to bring to your attention some important findings regarding CPU resource usage within our shared environment. Efficient utilization of platform resources is critical to maintaining optimal performance and ensuring fair access for all teams. 

Below is a summary of the key data we have identified: 

**Project:** XXXXXX
**CPU Core wasted:** XX
**CPU Core in use:** XX
**CPU Booked/Occupied:** XX

**Breakdown of key data** 

1. **CPU Core wasted**: This represents the amount of CPU resources that are allocated but not effectively utilized. It's essentially the unused capacity that could otherwise be available for other processes or teams
2. **CPU Core in use**: This is the actual CPU core usage by a specific process or application. It shows how much CPU power is being actively consumed by a namespace or workload
3. **CPU Booked**: This indicates the total amount of CPU resources that have been reserved for a particular namespace or application. These resources are set aside and are not available for use by other teams or processes, even if they are not being fully utilized

 **Why this matters**

As outlined in the Memorandum of Understanding (MoU), it is our collective responsibility to ensure that applications use platform resources efficiently, including CPU, RAM, and storage. The OpenShift Platform environment operates on shared resources available to all teams. 

If we continue to overuse CPU cores it’ll continue to prevent other teams from utilizing these shared resources, leading to inefficiencies and potential performance degradation for everyone along with: 

•	**Increased operational costs**: Wasted CPU resources contribute to higher operational costs. Even if the resources aren't actively used, maintaining them incurs costs for power, cooling, and data centre space. Efficient usage can lead to significant cost savings

•	**Reduced system stability**: Overallocation of CPU can lead to resource contention among applications. This might not only affect the performance of the over-allocating application but can also lead to stability issues across the entire platform, potentially affecting multiple teams

•	**Delayed scaling operations**: When CPU resources are tied up unnecessarily, scaling operations for other applications that need these resources to handle increased load can be delayed. This can affect the agility of the business to respond to demand spikes

•	**Inefficiency in resource allocation**: Continuous overallocation of resources leads to a culture of inefficiency where resources are not being utilized thoughtfully. This can slow down the overall innovation on the platform as fewer resources are available for experimenting with new solutions
 
**Actions required**
1.	**Review and plan**: Contact your technical lead and development team to review the wasted resources and develop a plan to adjust your usage. It is recommended you request an estimate of the associated cost for your development team to make the changes

2.	**Optimize usage**: Instruct your development team to optimize resource usage to ensure efficient allocation of platform resources as soon as possible

3.	**Report back to the Platform Team** that your resource optimization is completed within two months

Please refer your team to these guides for more help: 

•	[Application resource tuning ](https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/automation-and-resiliency/application-resource-tuning/)
•	[Managing resource quotas in Kubernetes: A complete guide ](https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/app-monitoring/managing-resource-quotas-in-kubernetes/)

By reducing CPU wastage, we can improve overall system performance, enhancing the speed and reliability of solutions across the board.

Thank you for your immediate attention to this matter. If you have any questions regarding this report, please contact us at PlatformServicesTeam@gov.bc.ca  

Best regards, 

Platform Services Team
