### ISSUE TITLE
OCP 4.14 Review Release Notes - Ian

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5005]
**Describe the issue**
Review the [OCP 4.14 Release Notes](https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html) for any changes that will impact the product teams, ops team, or platform services team. Also look for any exciting new features that community should know about.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Read the release notes. Add any bits you find interesting and needing of discussion as comments here.

**Identify any dependencies**
None

**Definition of done**
- [x] Fully read the release notes and added anything of interest as a comment here

**Comment by IanKWatts** [comment]
# could be problematic
Future restricted enforcement for pod security admission
    Will be enforced in next minor release (4.15)
    How to check if any workloads have pod security violations?
DeploymentConfig resources are now deprecated
    Still supported, but deprecated
    Users should begin preparing to change these to Deployments
API storage.k8s.io/v1beta1 is now storage.k8s.io/v1
RHEL 6 base image containers are not supported on RHCOS container hosts but are supported on RHEL 8 worker nodes. For more information, see the Red Hat Container Compatibility matrix.
    https://access.redhat.com/support/policy/rhel-container-compatibility?extIdCarryOver=true&sc_cid=701f2000001OH74AAG

# good
'oc login --web' to log in with browser instead of token
CronJob time zone setting is now GA
    .spec.timeZone
    https://docs.openshift.com/container-platform/4.14/nodes/jobs/nodes-nodes-jobs.html#nodes-nodes-jobs-creating-cron_nodes-nodes-jobs
CoreDNS now supports a 'protocolStrategy' field
    Set it to 'TCP' to avoid UDP responses that could be larger than the buffer size of 512 bytes
PDBs now support 'unhealthyPodEvictionPolicy: AlwaysAllow'
    to allow crashing pods to be evicted
    default is 'IfHealthyBudget'
