### ISSUE TITLE
Develop a report for teams to show their CPU / RAM usage

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#510]
Generate a PDF / image / HTML that shows project CPU Usage (possibly averaged over time?) and the CPU Requests. Highlight the slack or unused amount.

This report should be runnable by the dev team, or create reports they can access.

Data can come from Prometheus queries.

Inspired by
![kube-resource-report.png](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/330e1fd8-2ef9-4664-bfe0-ac15a291254b)

**Comment by stewartshea** [comment]
Doesn't something like this suffice? 
![image.png](https://images.zenhubusercontent.com/5882267651aa2c3057728119/eaf5afc2-1c82-40a0-88b7-c360838a3a92)

**Comment by sbarre-esit** [comment]
Yup, I think that would work. ETA on when all teams will have access to such a dashboard?

**Comment by wenzowski** [comment]
@stewartshea that looks like the dashboard I was referring to. Doesn’t compare usage against request/limit; serves a different purpose. Still really helpful and grateful to have access.

https://github.com/hjacobs/kube-resource-report
Is used by Zalando (that’s the Patroni people BTW) in production to solve for the exact cluster slack optimization problem @mitovskaol was requesting feedback on. Apologies if I misunderstood. I recall Henning Jacobs did a talk on this so there might be slides as well.

Since we already have Sysdig I fully support implementation there if that’s easier than Zalando’s helm charts (one less thing to maintain etc)

https://chat.pathfinder.gov.bc.ca/channel/devops-operations?msg=2eGzrEnyAZJvPKQ3r

![68F376C2-FFAE-48F5-AC10-8D905667F1B4](https://user-images.githubusercontent.com/597920/84540754-e7b46b00-acaa-11ea-99c3-aeed326d4ff0.png)

**Comment by wenzowski** [comment]
^ apologies if above is brusque; in a meeting. Happy to clarify as needed. Than you all for the wonderful work you do!

**Comment by wenzowski** [comment]
oh! @stewartshea was that dashboard updated in place?

Hard to see that low contrast text in screenshots on mobile. My bad! 
I see the details now. Awesome!
<img width="602" alt="Screen Shot 2020-06-12 at 3 00 46 PM" src="https://user-images.githubusercontent.com/597920/84549763-ad07fe00-acbd-11ea-8ef5-d500b3a06c63.png">

Yup, I think that would work.

/cc @matthieu-foucault

**Comment by stewartshea** [comment]
Hey @wenzowski @sbarre-esit 

Apologies for the delay, was up in the mountains the last few days! 

@wenzowski I will be making an adjustment to the dashboard panels (to show the percentage of request instead of limit). I do like Zalando's work as well, but I think we have all we need in Sysdig. Let me know if there's still a stat that you'd like to see and we can write up documentation on how to obtain it :) 

@sbarre-esit we are prioritising the outstanding bugs for it this week to release to more teams.

**Comment by tosazuwa** [comment]
Refer to #199

**Comment by lukegonis** [comment]
we are waiting to complete the testing of the fix and will revisit in mid September.

**Comment by jefkel** [comment]
Sysdig dashboards are targetted to fulfill this requirement, and are being rolled out slowly.
