### ISSUE TITLE
Update PDB docs with new Unhealthy Eviction Policy

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#5118]
**Describe the issue**
Update the PDB docs to include the new setting

```yaml
spec:
  unhealthyPodEvictionPolicy: AlwaysAllow
```

https://docs.openshift.com/container-platform/4.14/nodes/pods/nodes-pods-configuring.html#pod-disruption-eviction-policy_nodes-pods-configuring
https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/build-deploy-and-maintain-apps/maintain-an-application/#pdbs-pod-disruption-budgets

**What is the Value/Impact?**
Smoother OCP maintenance

**What is the plan? How will this get completed?**
PR against the docs page

**Identify any dependencies**
Review from Pilar

**Definition of done**
Docs updated

**Comment by vivekratan88** [comment]
deployed nginx deployment to run tests and created vivek-test namespace

**Comment by vivekratan88** [comment]
completed and tested in CLAB used readiness probe as an indicator for PDB and tested it. 

**Output:**

CLAB/vivek-test ~ $ oc get pods
NAME                     READY   STATUS    RESTARTS   AGE
nginx-5fb74b85df-5cpt4   0/1     Running   0          2m2s
nginx-5fb74b85df-7krwv   0/1     Running   0          2m2s
nginx-5fb74b85df-q8dxs   0/1     Running   0          2m2s
CLAB/vivek-test ~ $ oc get poddisruptionbudgets
NAME     MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
my-pdb   2               N/A               0                     132m
CLAB/vivek-test ~ $ oc get pods -o wide
NAME                     READY   STATUS    RESTARTS   AGE     IP             NODE                  NOMINATED NODE   READINESS GATES
**nginx-5fb74b85df-5cpt4**   0/1     Running   0          3m47s   xx.xx.xx.xxx   **mcs-clab-app-02.dmz**   <none>           <none>
nginx-5fb74b85df-7krwv   0/1     Running   0          3m47s   xx.xx.xx.xxx   mcs-clab-app-01.dmz   <none>           <none>
nginx-5fb74b85df-q8dxs   0/1     Running   0          3m47s   xx.xx.xx.xxx   mcs-clab-app-03.dmz   <none>           <none>
CLAB/vivek-test ~ $ **oc adm drain --delete-emptydir-data --ignore-daemonsets mcs-clab-app-02.dmz**
node/mcs-clab-app-02.dmz cordoned
Warning: ignoring DaemonSet-managed Pods: openshift-bcgov-encase/encase-s94p2, openshift-bcgov-nagios-dhcp/dhcp-check-pvb79, openshift-bcgov-sysdig-agent/sysdig-agent-56bzr, openshift-bcgov-trident/trident-node-linux-5f22p, openshift-bcgov-vrops/vrops-g68vs, openshift-cluster-node-tuning-operator/tuned-dd8q5, openshift-dns/dns-default-qk2b8, openshift-dns/node-resolver-hcrrd, openshift-file-integrity/aide-advsol-fileintegrity-2d6cs, openshift-image-registry/node-ca-24sgm, openshift-ingress-canary/ingress-canary-8qds9, openshift-logging/collector-7vdw4, openshift-machine-config-operator/machine-config-daemon-57s67, openshift-monitoring/node-exporter-4ttmb, openshift-multus/multus-additional-cni-plugins-brl54, openshift-multus/multus-hpnts, openshift-multus/network-metrics-daemon-2ckg4, openshift-network-diagnostics/network-check-target-pmftb, openshift-sdn/sdn-45pq8, stackrox/collector-xn9ks
**evicting pod vivek-test/nginx-5fb74b85df-5cpt4**
evicting pod openshift-bcgov-cerberus/cerberus-server-1
evicting pod openshift-bcgov-entitlements/benny-operator-update-check-28825741-wwbjz
evicting pod openshift-bcgov-entitlements/benny-operator-update-check-28825801-tkdb7
evicting pod openshift-bcgov-entitlements/benny-operator-update-check-28825861-k6x8p
evicting pod openshift-bcgov-grafana/grafana-datasource-check-28825880-n6p8v
evicting pod openshift-bcgov-nagios/long-term-metrics-28825860-8jqnp
evicting pod openshift-bcgov-nagios/long-term-metrics-host-28825830-rhpvq
evicting pod openshift-bcgov-nagios/monitor-28825880-jhtpt
evicting pod openshift-bcgov-vault/vault-lab-2
evicting pod openshift-bcgov-vault/vault-lab-agent-injector-54ff7596d4-6gcvv
evicting pod openshift-gitops/cluster-785d4fb9f6-9hbxz
evicting pod openshift-gitops/openshift-gitops-server-78cf4c8bcd-229w9
evicting pod openshift-operator-lifecycle-manager/collect-profiles-28825845-8r89c
evicting pod openshift-operator-lifecycle-manager/collect-profiles-28825860-d6k9k
evicting pod openshift-operator-lifecycle-manager/collect-profiles-28825875-kp774
evicting pod openshift-pipelines/tekton-pipelines-webhook-67b469885c-qnwwj
evicting pod e31b6b-dev/hippo-repo1-incr-28825680-vrqsr
evicting pod dbfa0f-dev/deployment-restarter-28825845-9vkdt
evicting pod dbfa0f-dev/deployment-restarter-28825860-cnl4r
evicting pod e7c518-dev/siebel-sai-0
evicting pod dbfa0f-dev/deployment-restarter-28825875-z7c47
evicting pod dbfa0f-dev/vault-test-6dc45d5b9b-lfjvt
evicting pod devops-artifactory/patroni-001-1
evicting pod devops-xray/patroni-001-0
evicting pod kyverno/kyverno-cleanup-cluster-admission-reports-28825880-xdfkx
evicting pod f4423b-test/qsos-clab-g-l-test-bitnami-pg-0
evicting pod ministry-viewer/ministry-viewer-update-job-28825741-rd62k
evicting pod ministry-viewer/ministry-viewer-update-job-28825861-gwp6n
evicting pod ministry-viewer/ministry-viewer-update-job-28825801-2bnjr
evicting pod kyverno/kyverno-cleanup-admission-reports-28825880-gcz9h
pod/benny-operator-update-check-28825801-tkdb7 evicted
pod/long-term-metrics-28825860-8jqnp evicted
pod/benny-operator-update-check-28825861-k6x8p evicted
pod/grafana-datasource-check-28825880-n6p8v evicted
pod/monitor-28825880-jhtpt evicted
pod/long-term-metrics-host-28825830-rhpvq evicted
pod/benny-operator-update-check-28825741-wwbjz evicted
I1021 16:20:46.018550  978573 request.go:696] Waited for 1.000209519s due to client-side throttling, not priority and fairness, request: POST:https://api.clab.devops.gov.bc.ca:6443/api/v1/namespaces/openshift-operator-lifecycle-manager/pods/collect-profiles-28825860-d6k9k/eviction
pod/collect-profiles-28825845-8r89c evicted
pod/collect-profiles-28825860-d6k9k evicted
pod/nginx-5fb74b85df-5cpt4 evicted
pod/collect-profiles-28825875-kp774 evicted
pod/vault-lab-agent-injector-54ff7596d4-6gcvv evicted
pod/cluster-785d4fb9f6-9hbxz evicted
pod/hippo-repo1-incr-28825680-vrqsr evicted
pod/deployment-restarter-28825845-9vkdt evicted
pod/openshift-gitops-server-78cf4c8bcd-229w9 evicted
pod/deployment-restarter-28825860-cnl4r evicted
pod/deployment-restarter-28825875-z7c47 evicted
pod/patroni-001-0 evicted
pod/kyverno-cleanup-cluster-admission-reports-28825880-xdfkx evicted
pod/ministry-viewer-update-job-28825861-gwp6n evicted
pod/ministry-viewer-update-job-28825741-rd62k evicted
pod/ministry-viewer-update-job-28825801-2bnjr evicted
pod/kyverno-cleanup-admission-reports-28825880-gcz9h evicted
pod/vault-lab-2 evicted
I1021 16:20:56.452263  978573 request.go:696] Waited for 1.190320439s due to client-side throttling, not priority and fairness, request: GET:https://api.clab.devops.gov.bc.ca:6443/api/v1/namespaces/devops-artifactory/pods/patroni-001-1
I1021 16:21:07.452501  978573 request.go:696] Waited for 1.191514507s due to client-side throttling, not priority and fairness, request: GET:https://api.clab.devops.gov.bc.ca:6443/api/v1/namespaces/devops-artifactory/pods/patroni-001-1
pod/cerberus-server-1 evicted
pod/tekton-pipelines-webhook-67b469885c-qnwwj evicted
pod/vault-test-6dc45d5b9b-lfjvt evicted
pod/patroni-001-1 evicted
pod/siebel-sai-0 evicted
pod/qsos-clab-g-l-test-bitnami-pg-0 evicted
node/mcs-clab-app-02.dmz drained

**Comment by vivekratan88** [comment]
PR : https://github.com/bcgov/platform-developer-docs/pull/287
