### ISSUE TITLE
OCP 4.16 Review Release Notes - Vivek

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#5363]
**Describe the issue**
We're doing a double upgrade this round.

Review the [OCP 4.15 Release Notes](https://docs.redhat.com/en/documentation/openshift_container_platform/4.15/html/release_notes/ocp-4-15-release-notes) and [OCP 4.16 Release Notes](https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html/release_notes/ocp-4-16-release-notes) for any changes that will impact the product teams, ops team, or platform services team. Also look for any exciting new features that community should know about.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Read the release notes. Add any bits you find interesting and needing of discussion as comments here.

**Identify any dependencies**
None

**Definition of done**
- [ ] Fully read the release notes and added anything of interest as a comment here

**Comment by vivekratan88** [comment]
### **OpenShift 4.15 Key Features and Updates**

The OpenShift 4.15 release introduces several important features, updates, and deprecations designed to improve usability, performance, and integration with other platforms. Below are the main changes and new capabilities:

---

#### **1. vSphere Integration with Agent-based Installer**
- **What’s new:** OpenShift 4.15 allows users to configure a vSphere-based cluster during the Agent-based installation process. Specifically, it supports the configuration of the `install-config.yaml` file to enable vSphere integration, making it easier to deploy OpenShift clusters on vSphere environments.
- **Why this matters:** This integration streamlines the installation process for users running OpenShift on vSphere, automating the setup of virtual machines and simplifying cluster creation within VMware-based environments.

---

#### **2. Dell iDRAC BMC Integration for RAID Configuration**
- **What’s new:** During an installer-provisioned installation on bare metal, users can now leverage Dell's iDRAC Baseboard Management Controller (BMC) using the Redfish protocol to configure RAID (Redundant Array of Independent Disks) settings.
- **Why this matters:** This is particularly useful for bare-metal OpenShift installations, where users can automate the configuration of their disk storage layout before installation begins, ensuring optimized storage configuration from the outset without needing manual intervention.

---

#### **3. OperatorHub Support for Microsoft Entra Workload Identity**
- **What’s new:** OpenShift 4.15 enhances OperatorHub by detecting when a cluster running on Azure is configured with Microsoft Entra Workload Identity. Upon detection, users are provided with a "Cluster in Workload Identity / Federated Identity Mode" notification, along with additional instructions for installing Operators to ensure they function correctly within this environment. The Operator Installation page has also been updated to include fields for Azure credentials.
- **Why this matters:** This integration makes it easier for users running OpenShift on Azure to manage identities, ensuring that Operators are properly configured to work in an Azure-based identity context, improving security and simplifying credential management.

---

#### **4. Pipeline History and Logs via Tekton Results**
- **What’s new:** OpenShift 4.15 introduces the ability to view pipeline history and logs in the OpenShift Dashboard, sourced from Tekton Results, without requiring the `PipelineRun` Custom Resources (CRs) to be present in the cluster.
- **Why this matters:** This improvement simplifies monitoring and troubleshooting of pipelines by providing easier access to pipeline execution history and logs, even in cases where the `PipelineRun` objects are not retained. It reduces the complexity of managing logs, ensuring developers have access to the necessary information for debugging and improving their CI/CD workflows.

---

#### **5. CoreDNS Metrics Deprecation and Removal**
- **What’s new:** CoreDNS has been updated from version 1.10.1 to 1.11.1. With this update, certain CoreDNS metrics are deprecated and removed, including `coredns_forward_healthcheck_failures_total`, `coredns_forward_requests_total`, `coredns_forward_responses_total`, and `coredns_forward_request_duration_second`.
- **Why this matters:** The deprecation and removal of these metrics are part of a larger effort to improve the performance and resource efficiency of OpenShift clusters. Users who rely on these metrics for monitoring or alerting may need to update their configurations or explore alternative metrics provided by CoreDNS 1.11.1.

---

#### **6. Red Quay for Image Lifecycle Management**
- **What’s new:** OpenShift 4.15 introduces enhancements to Red Quay, including the ability to perform image pruning at the repository level and improved integration with OpenID Connect (OIDC) for team synchronization.
- **Why this matters:** Image lifecycle management has been improved, allowing users to manage the lifecycle of container images in a more granular way. These improvements help optimize storage and ensure that outdated or unused images are pruned automatically, improving resource utilization and operational efficiency.

---

#### **7. Logging 5.9 - Enhanced Search Across Multiple Namespaces**
- **What’s new:** The OpenShift 4.15 release includes updates to the Logging 5.9 stack, allowing users to search across multiple namespaces within the OpenShift Web Console's Observability UI (Dev Perspective -> Observability UI).
- **Why this matters:** This update simplifies troubleshooting and observability by enabling users to search logs across multiple namespaces in one go. This is especially helpful for larger, multi-namespace environments where logs need to be aggregated and searched from different parts of the cluster.

---

#### **8. Red Hat Build of Keycloak (Built on Quarkus)**
- **What’s new:** OpenShift 4.15 introduces a new build of Keycloak, Red Hat’s enterprise identity and access management solution, that is built on the Quarkus framework. This build promises better performance, reduced resource consumption, and a more streamlined user experience.
- **Why this matters:** The Quarkus-based build of Keycloak delivers faster startup times, reduced memory footprint, and improved management of Single Sign-On (SSO) capabilities. This allows users to secure their OpenShift applications with stronger, more efficient identity management.

---

#### **9. Persistent Volume Claim (PVC) Retrospective Assignment**
- **What’s new:** In OpenShift 4.15, if a Persistent Volume Claim (PVC) is pending due to a lack of a default StorageClass, the system will retroactively assign the PVC to the default StorageClass.
- **Why this matters:** This feature reduces the administrative burden on users, ensuring that PVCs are automatically assigned to the default StorageClass when no other specific StorageClass is set, helping avoid delays and errors in provisioning storage.

---

#### **10. Status Management for EgressFirewall and AdminPolicyBasedExternalRoute CR**
- **What’s new:** OpenShift 4.15 enhances the status management for the `EgressFirewall` and `AdminPolicyBasedExternalRoute` Custom Resources (CRs). The `status.status` field now provides more detailed feedback:
   - If any failure is detected, the `status.status` field is set to `failure`.
   - If no failures are reported and not all nodes have reported their status, the field remains empty.
   - If all nodes report success, the field is set to `success`.
   - The `status.messages` field now lists node-specific messages by default.
- **Why this matters:** This update makes it easier to track the status of network policies and external routes, allowing administrators to quickly identify configuration issues and take corrective actions.

---

### **Registry and Logging Enhancements**

#### **1. Support for Private Storage Endpoint on Azure**
- **What’s new:** The Image Registry Operator in OpenShift 4.15 now supports using private storage endpoints on Azure. This feature allows users to configure private endpoints for storage accounts when deploying OpenShift on private Azure clusters.
- **Why this matters:** This is important for security-conscious organizations that need to keep their image registries and storage traffic within private networks. It helps eliminate the need to expose public-facing storage endpoints, improving the security of the OpenShift environment.

#### **2. Log Linking Enabled by Default**
- **What’s new:** OpenShift 4.15 enables log linking by default. This feature gives users direct access to container logs from the OpenShift Web Console, making it easier to view the logs of containers running in the cluster.
- **Why this matters:** Log linking improves the developer and operator experience by making it simpler to correlate events and logs, facilitating faster troubleshooting and monitoring of applications.

---

### **Other Notable Changes and Deprecations**

#### **1. HAProxy No Strict-Limits Variable**
- **What’s new:** With the transition to HAProxy 2.6, OpenShift now enforces the strict-limits configuration, which was previously a user-configurable option. The strict-limits setting controls how the maximum number of connections is managed by HAProxy.
- **Why this matters:** Users no longer have control over strict-limits settings. This change aims to prevent unrecoverable errors that could occur when connection limits are exceeded. The enforcement of these settings provides better stability and predictability in handling connections.

#### **2. Must-Gather Storage Limit Default**
- **What’s new:** OpenShift 4.15 introduces a default storage limit for the `oc adm must-gather` command, capping it at 30% of the node's storage capacity. Administrators can adjust this limit using the `--volume-percentage` flag.
- **Why this matters:** This new default ensures that the `must-gather` command doesn’t overload nodes with excessive data collection, which is important for managing system performance during troubleshooting. Administrators can still tweak the limit if more data is needed for specific debugging scenarios.

#### **3. Deprecation of OpenShift SDN Network Plugin**
- **What’s new:** OpenShift SDN (Software-Defined Networking) is deprecated in OpenShift 4.15. It is no longer an option for new installations, and it will be fully removed in a future release. Users are encouraged to migrate to OVN Kubernetes as an alternative.
- **Why this matters:** OpenShift SDN has been deprecated due to the growing adoption of OVN Kubernetes, which offers better performance, scalability, and integration with Kubernetes. Existing OpenShift SDN users should plan to migrate to OVN Kubernetes to ensure continued support and to take advantage of its advanced features.

#### **4. Deprecation of `oc registry info` Command**
- **What’s new:** The `oc registry info` command is deprecated in OpenShift 4.15. Users should now use `oc get imagestream -n openshift` to obtain details about the integrated OpenShift image registry.
- **Why this matters:** This change simplifies the OpenShift CLI and encourages users to adopt the new, recommended method for accessing image registry information.

**Comment by vivekratan88** [comment]
### **Key Features and Updates in OpenShift 4.16**

---

#### **1. Optional Additional Tags for VMware vSphere**
- **What’s new:** OpenShift 4.16 introduces the ability to add up to ten additional tags to virtual machines (VMs) provisioned in a VMware vSphere cluster. These tags are in addition to the unique cluster-specific tag, which helps identify and manage VMs when a cluster is decommissioned.
- **Why this matters:** This feature allows users to enhance the organization and management of vSphere VMs by providing additional metadata for identification and tracking. The ability to add more tags increases flexibility in managing resources in environments with large numbers of VMs, simplifying tasks such as categorizing or automating workflows.

---

#### **2. Configuring Pod Placement to Check Network Connectivity**
- **What’s new:** OpenShift 4.16 allows users to configure pod placement to periodically test network connectivity among cluster components. This is done by using the **Cluster Network Operator (CNO)** to create a `network-check-source` deployment and a `network-check-target` daemon set. Users can configure nodes with specific node selectors to run the source and target pods that perform network connectivity checks.
- **Why this matters:** This feature helps ensure the network connectivity between OpenShift cluster components is continuously validated. It provides an automated way to detect network issues early and helps maintain a healthy and stable networking environment across all nodes and pods.

---

#### **3. vSphere CSI: Change in Maximum Number of Snapshots**
- **What’s new:** The VMware vSphere Container Storage Interface (CSI) now allows users to change the maximum number of snapshots per volume. Previously, the default maximum was set to 3 snapshots. With OpenShift 4.16, users can increase this number up to 32 snapshots per volume, with additional granular control over the number of snapshots for vSAN and Virtual Volume (VVOL) datastores.
- **Why this matters:** This improvement provides greater flexibility in managing storage for stateful applications, enabling users to take more frequent or additional snapshots for backup and recovery purposes. By supporting up to 32 snapshots, OpenShift gives users more options for protecting their data and ensuring application continuity.

---

#### **4. Machine Config Operator: Garbage Collection of Unused Rendered Machine Configs**
- **What’s new:** OpenShift 4.16 introduces the ability to garbage collect unused rendered machine configs. Using the `oc adm prune renderedmachineconfigs` command, administrators can view unused machine configs and selectively delete them to avoid clutter. This helps maintain a cleaner environment and improve performance.
- **Why this matters:** As machine configurations can accumulate over time, especially in dynamic or large environments, having too many unused rendered configs can lead to operational confusion, disk space issues, and performance degradation. This feature allows administrators to maintain a more manageable configuration set, improving cluster performance and administration.

---

#### **5. Security Update: Unauthenticated Users Removed from Some Cluster Roles**
- **What’s new:** OpenShift 4.16 introduces stricter access control by removing unauthenticated users from certain cluster roles. Previously, unauthenticated users could access specific cluster roles necessary for certain features. This change adds an extra layer of security by limiting access to cluster resources.
- **Why this matters:** This update strengthens cluster security by limiting access to sensitive resources to authenticated users only. While some use cases might require granting unauthenticated access to specific roles, this should only be enabled when absolutely necessary. The change applies to new clusters, and existing clusters are not affected unless manually updated.

---

#### **6. Scaffolding Tools for Helm-based Operator Projects**
- **What’s new:** OpenShift 4.16 introduces scaffolding tools designed to support the creation of Helm-based Operator projects. Helm, a popular package manager for Kubernetes, is now better integrated into the OpenShift Operator ecosystem, making it easier to build, deploy, and manage Helm-based Operators.
- **Why this matters:** These tools help developers create and manage Helm charts for Kubernetes and OpenShift, improving the developer experience and enabling easier integration of Helm with the broader Operator framework. This simplifies the process of packaging and distributing applications as Operators, thus enhancing the modularity and reuse of Kubernetes-based applications.

---

#### **7. Cluster Samples Operator Deprecated**
- **What’s new:** The **Cluster Samples Operator** has been deprecated in OpenShift 4.16. It will no longer manage non-S2I (Source-to-Image) samples such as image streams and templates. However, existing S2I templates and image streams will continue to receive updates until the Cluster Samples Operator is removed in a future release.
- **Why this matters:** The deprecation signals a shift towards using more modern and flexible mechanisms for deploying and managing OpenShift resources. Users currently relying on non-S2I templates and image streams will need to transition to alternative methods for managing their sample applications. This change is in line with Red Hat’s focus on streamlining the OpenShift experience and pushing for more standardized ways of deploying applications.

---

#### **8. Dell iDRAC Driver for BMC Addressing Removed**
- **What’s new:** OpenShift 4.16 removes the Dell iDRAC driver for Baseboard Management Controller (BMC) addressing. While OpenShift still supports BMC addressing for Dell servers using `idrac-virtualmedia`, Redfish, and IPMI, the specific iDRAC driver for addressing is no longer available.
- **Why this matters:** Users who rely on Dell iDRAC for managing hardware must now use the newer supported methods (Redfish or IPMI) for BMC addressing. This change aligns OpenShift with more modern standards for managing hardware in bare-metal environments, ensuring better long-term compatibility and support for hardware management.

---

#### **9. Removal of Dedicated Service Monitors for Core Platform Monitoring**
- **What’s new:** The ability to configure **dedicated service monitors** for core platform monitoring has been removed in OpenShift 4.16. This functionality, previously configurable through the `cluster-monitoring-config` config map object in the `openshift-monitoring` namespace, is no longer available.
- **Why this matters:** Prometheus functionality has been improved to ensure that alerts and time aggregations are more accurate by default. This update eliminates the need for dedicated service monitors and simplifies the core monitoring configuration. The improved Prometheus functionality ensures that monitoring remains robust, while also streamlining the configuration and operation of monitoring services.
