### ISSUE TITLE
Devhub Issue: Getting human support for issues not covered by devops-requests [short description here]

### ISSUE THREAD

**Issue by chrsuthe** [BCDevOps/developer-experience#588]
> path: (do not delete) https://github.com/BCDevOps/developer-experience/blob/master/docs/HumanHelp.md
 > (do not delete) devhub page: /Getting-human-support-for-issues-not-covered-by-devops-requests

## Devhub Content Issue

hello, I am not really sure where to start.  My name is Christine Sutherland with the Web Access Management team in CITZ. We have a new project called SiteMinder Access Gateway (SmAG) that will require the creation of automation scripts.  The consultants have requested that we create a repository in the DevOps GitHub infrastructure in order to hold and manage the code.  I am not completely clear on the process of requesting or order this service.  I have attempted to go and request a new repository but do not have an account with  BCGov DevOps.  If there are detailed instructions I would be happy to follow them if pointed to any documentation.

Thank you,

Christine Sutherland
christine.sutherland@gov.bc.ca

**Comment by patricksimonian** [comment]
@caggles

**Comment by caggles** [comment]
Hi @chrsuthe ! We have a special repo full of ticket templates for these sorts of requests, which you can find here: https://github.com/BCDevOps/devops-requests/issues/new/choose

Generally speaking, new teams coming to work on the platform create their repos in the bcgov organization, not in BCDevOps. If the bcgov org works for you, then you'll want to request membership in the org. We don't normally allow self-requests, so if there's someone already in the org who can make that request for you, please have them open the membership ticket on your behalf. Otherwise, please speak to @mitovskaol for an exception! Once you get into the organization, you'll be able to make a repo yourself - no further requests are required!

If you do believe that you require your repo to be in the BCDevOps org, we'll need to discuss that further.

If you have any further questions, please feel free to reach out to me, @patricksimonian, @ShellyXueHan or @mitovskaol. Email or Rocketchat works fine as a contact method for any of us!

**Comment by caggles** [comment]
And one more thing! As a new team, you may find it helpful to read through the documentation you can find here: https://developer.gov.bc.ca/Onboarding-Journey - it provides some additional information about the various devops-related resources we offer!
