### ISSUE TITLE
OpenShift Namespace House Keeping

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#61]
Hi all,

Platform Service team is currently cleaning namespaces on OpenShift that are either a sandbox or prove-of-concept. If you are tagged here, that means you are the admin user of the namespaces.

If the namespaces listed below are still active, please respond to this ticket and provide the following information:
- namespace and project name:
- email for Product Owner:
- email for Technical Lead:
- date for the namespaces to be removed:

If no response received after two weeks, we will remove the namespace.

`ag-devops-lab-*`:
Users: @rloisell @nataliyashapka @mahoneyg @itchison

`agehlers-sandbox`:
Users: @sheaphillips @VarekBoettcher @WadeBarnes

`csnr-dmod-*`:
Users: @cvarjao @matthewhall78 @marklise @parc-jason @jujaga @loneil

`devops-sandbox-*`:
Users: @sheaphillips

`l8g1vt-*`:
Users: @ActionAnalytics

`mcfd-icpm-smbs-*`:
Users: @derekyau @cvarjao

`migration-test`:
Users: @system:admin @jefkel

`oaujjs-*`:
Users: @bakerpj @cmcglone @danielpsantiago @andyahope

`steve-test`:
Users: @system:admin

`upk4nr-*`:
Users: @thorwolpert @WalterMoar

`xxtzwx-*`:
Users: @mark-walle @danpollock @a-ell @ryrjanes @BJenning

`zklvz6-*`:
Users: @patricksimonian

`ak73dc-sandbox`:
Users: @stewartshea, @j-pye, @mitovskaol

`csnr-devops-lab-*`:
Users: @actionanalytics @cvarjao @garywong-bc @kuanfandevops @poornima-sivanand

`xzyxml-*`:
Users: @dhruvio @sutherlanda

`fc7m4g-*`:
Users: @jdou

**Comment by derekyau** [comment]
Hi Shelly,

As for `mcfd-icpm-smbs` you are free to remove this namespace.

Thanks,
-Derek


On November 22, 2019 at 3:52:12 PM, Shelly Han (notifications@github.com)
wrote:

Hi all,

Platform Service team is currently cleaning namespaces on OpenShift that
are either a sandbox or prove-of-concept. If you are tagged here, that
means you are the admin user of the namespaces.

If the namespaces listed below are still active, please respond to this
ticket and provide the following information:

   - namespace and project name:
   - email for Product Owner:
   - email for Technical Lead:
   - date for the namespaces to be removed:

If no response received after two weeks, we will remove the namespace.

ag-devops-lab-*:
Users: @rloisell <https://github.com/rloisell> @nataliyashapka
<https://github.com/nataliyashapka> @mahoneyg <https://github.com/mahoneyg>
@itchison <https://github.com/itchison>

agehlers-sandbox:
Users: @sheaphillips <https://github.com/sheaphillips> @VarekBoettcher
<https://github.com/VarekBoettcher> @WadeBarnes
<https://github.com/WadeBarnes>

csnr-dmod-*:
Users: @cvarjao <https://github.com/cvarjao> @matthewhall78
<https://github.com/matthewhall78> @marklise <https://github.com/marklise>
@parc-jason <https://github.com/parc-jason> @jujaga
<https://github.com/jujaga> @loneil <https://github.com/loneil>

devops-sandbox-*:
Users: @sheaphillips <https://github.com/sheaphillips>

l8g1vt-*:
Users: @ActionAnalytics <https://github.com/ActionAnalytics>

mcfd-icpm-smbs-*:
Users: @derekyau <https://github.com/derekyau> @cvarjao
<https://github.com/cvarjao>

migration-test:
Users: @System <https://github.com/System>:admin @jefkel
<https://github.com/jefkel>

oaujjs-*:
Users: @bakerpj <https://github.com/bakerpj> @cmcglone
<https://github.com/cmcglone> @danielpsantiago
<https://github.com/danielpsantiago> @AndyAHope
<https://github.com/AndyAHope>

steve-test:
Users: @System <https://github.com/System>:admin

upk4nr-*:
Users: @thorwolpert <https://github.com/thorwolpert> @WalterMoar
<https://github.com/WalterMoar>

xxtzwx-*:
Users: @mark-walle <https://github.com/mark-walle> @danpollock
<https://github.com/danpollock> @a-ell <https://github.com/a-ell> @ryrjanes
<https://github.com/ryrjanes> @BJenning <https://github.com/BJenning>

zklvz6-*:
Users: @patricksimonian <https://github.com/patricksimonian>

ak73dc-sandbox:
Users: @stewartshea <https://github.com/stewartshea>, @j-pye
<https://github.com/j-pye>, @mitovskaol <https://github.com/mitovskaol>

csnr-devops-lab-*:
Users: @ActionAnalytics <https://github.com/ActionAnalytics> @cvarjao
<https://github.com/cvarjao> @garywong-bc <https://github.com/garywong-bc>
@kuanfandevops <https://github.com/kuanfandevops> @poornima-sivanand
<https://github.com/poornima-sivanand>

xzyxml-*:
Users: @dhruvio <https://github.com/dhruvio> @sutherlanda
<https://github.com/sutherlanda>

fc7m4g-*:
Users: @jdou <https://github.com/jdou>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/BCDevOps/developer-experience/issues/61?email_source=notifications&email_token=AADOH23CTWXWPF7RTYJON7TQVBWCZA5CNFSM4JQXJ3YKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H3QRFUQ>,
or unsubscribe

**Comment by sutherlanda** [comment]
Hi Shelley,

For xzyxml-*:

Namespace: Digital Marketplace (DIG_MKT)
Product Owner: Zachary Woodward (zachary.woodward@gov.bc.ca)
Technical Lead: Andrew Sutherland (andrew.l.sutherland@gov.bc.ca)
Date to remove: Please don't remove.  We only set this up a few weeks ago for an ongoing project.  Thanks.

**Comment by mark-walle** [comment]
- namespace and project name: `xxtzwx-*` gdx-analytics-sandbox
   - email for Product Owner: Dan Pollock @danpollock 
   - email for Technical Lead: Mark Walle @mark-walle 
   - date for the namespaces to be removed: 2020-05-29

**Comment by thorwolpert** [comment]
This was buried amongst my GitHub messages, so hopefully I'm still in time.


   - namespace and project name: upk4nr & all BC Registry renewal projects
   - email for Product Owner: Walter.Moar@gov.bc.ca
   - email for Technical Lead: thor@wolpert.ca
   - date for the namespaces to be removed: 2021-01-31

**Comment by mitovskaol** [comment]
Please keep the `ak73dc-sandbox` namespace. 
Users: @stewartshea, @j-pye, @mitovskaol

**Comment by matthewhall78** [comment]
Hi,

  *   namespace and project name: csnr-dmod-*
  *   email for Product Owner: matthew.hall@gov.bc.ca
  *   email for Technical Lead: clecio.varjao@gov.bc.ca
  *   date for the namespaces to be removed: This repo is going to be a showcase app for Document Management Common Service.  It started as a POC but since then my team has been developed and formalized.  We will need to keep this.

Users: @cvarjao<https://github.com/cvarjao> @matthewhall78<https://github.com/matthewhall78> @marklise<https://github.com/marklise> @parc-jason<https://github.com/parc-jason> @jujaga<https://github.com/jujaga> @loneil<https://github.com/loneil>


Matthew Hall | (250) 896-4059

**Comment by cmcglone** [comment]
Hello, this project/namespace is still active, please do not remove.

namespace and project name: oaujjs-*:
email for Product Owner: Chris.McGlone@gov.bc.ca<mailto:Chris.McGlone@gov.bc.ca>

  *   email for Technical Lead: Chris.McGlone@gov.bc.ca<mailto:Chris.McGlone@gov.bc.ca>
  *   Date for the namespaces to be removed: 2020-11-26
  *   Users: @bakerpj<https://github.com/bakerpj> @cmcglone<https://github.com/cmcglone> @danielpsantiago<https://github.com/danielpsantiago> @AndyAHope<https://github.com/AndyAHope>

Chris McGlone
Application Manager
Technical Infrastructure and Service Operations
Information Management Branch
Corporate Services Division
Ministry of Citizens’ Services
4000 Seymour Place, E123
Victoria, BC
Ph: 250-952-8160 Cell: 250-514-1295
E-Mail: Chris.McGlone@gov.bc.ca<mailto:Chris.McGlone@gov.bc.ca>

**Comment by rloisell** [comment]
Hey Shelly,

For the following:

ag-devops-lab-*:
Users: @rloisell<https://github.com/rloisell> @nataliyashapka<https://github.com/nataliyashapka> @mahoneyg<https://github.com/mahoneyg> @itchison<https://github.com/itchison>

  *   namespace and project name: ag-devops-lab-*
  *   email for Product Owner: @Hewitt, Justin AG:EX<mailto:Justin.Hewitt@gov.bc.ca>
  *   email for Technical Lead: Ryan.Loiselle@gov.bc.ca
  *   date for the namespaces to be removed: Please don’t remove. This is our sectors lab space where Architecture, SREs and various project teams have a place to test, learn,  research, or stub out components. A place for AG/PSSG ISB  to stay involved with evolving DevOps practices without requiring access to production Justice and Public Safety Sector IT systems compute space (or their Dev/Test pipelines and environment).

Ryan Loiselle
Solution Architect
Strategic Initiatives || Information Systems Branch || Ministry of Attorney General and Ministry of Public Safety and Solicitor General || BC Gov
Phone: 778.698.3143 (Desk UC) 250.380.8656 (Cell)

**Comment by jdou** [comment]
Hello,
We would like to graduate out of the sandbox for fc7m4g-*
The application is now live at crdbikecounts.ca

  - namespace and project name:fc7m4g-*
   - email for Product Owner:jdouillard@crd.bc.ca
   - email for Technical Lead:jdouillard@crd.bc.ca


Thanks!

**Comment by cvarjao** [comment]
Please don't delete `csnr-devops-lab-*`. I share that namespace with other IITD folks as a sandbox /lab namespace.
