### ISSUE TITLE
BCSC Team support

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#651]
### Background
This is a support ticket for BCSC team to help update a sample application dependency. Please fill in more details.

**Comment by yhfreeman** [comment]
Results / updates:

[Dec 16, 2020]
- The badge issue was covered where we added the required badge at the beginning of the README file and checked in this commit on the default branch.

- For the dependency upgrade issue that requires manual upgrade, we decided to leave it as it is because manually upgrading dependencies is not a light task AND does require someone who is much familiar with the code / app (so behaviours / functionalities can be thoroughly tested after the manual upgrade).

[Jan 06, 2021]
- Dependabot PR request on vulnerability-related dependency update
