### ISSUE TITLE
Pathfinder StatusPage (status.pathfinder.gov.bc.ca) migration decision

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#790]
**Describe the issue**
status.pathfinder.gov.bc.ca service is a customized status page for the pathfinder platform.  With the re-vamp of cluster monitoring and status visualization, does this application still provide value?

**Additional context/questions**
- Identify features that are being used

**Definition of done**
- Decision on decomission, migrate, modify for the Custom status indicator page.

**Comment by stewartshea** [comment]
Since we've decided that users don't care about the overall Load page and the platform admins can get this from Sysdig, that feature is no longer required. The notification features are still used, but this can likely be revamped: 
- Post to uptime robot an announcement
- Post to rocket chat channel

We can dramatically simplify those features and drop the grafana dashboard altogether.

**Comment by mitovskaol** [comment]
We have discussed the future plans for the status.pathfinder.gov.bc.ca page with the Team and the decision was made **not to migrate it** to OCP 4.  Its current functionality will be split between the new uptime robot dashboard and the internal scripts that the Platform Ops Team uses to monitor the Platform. The page will be retired at the end of life of OCP 3 Platform.
