### ISSUE TITLE
Fix OCP4 SSO Redirect

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/developer-experience#827]
**Describe the issue**
The github issue that OCP4 SSO redirects to when you are not a member of the BCDevOps org has been modified to be used for OCP3 project removals.  This should point to an issue to request access to the BCDevOps Github Organization.

**Definition of done**
- [ ] Create or Update Existing Issue for Requesting Membership in the BCDevOps Org
- [ ] Update Keycloak SSO redirect to point to the proper issue

**Comment by j-pye** [comment]
@caggles @mitovskaol Could one of you please provide the issue and link? Once that's provided myself or Shelly have access to the realm to update the redirects. Thanks

**Comment by caggles** [comment]
I would very much recommend using the "new issue" page (https://github.com/BCDevOps/devops-requests/issues/new/choose) as the landing page for anything like this, rather than linking directly to an issue. This is because some of the templated information is actually baked into the URL which means that, if we change that information in the template, those changes don't get propagated through the links in places like SSO (which is how we recently ended up with a ticket assigned to todd, lol). So, generally speaking, let's drop everyone on the "new issue" page, perhaps with some relevant note about the specific issue they're looking for.

**Comment by mitovskaol** [comment]
@j-pye Please test if this is still relevant and if not, close the ticket.

**Comment by j-pye** [comment]
This appears to be working as expected now in Silver. Tested with a non-org GH user account.
