### ISSUE TITLE
Monitor and document aqua resource usage in KLAB

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/developer-experience#896]
With the platform running in KLAB, review the performance metrics of the components and document any recommended resource adjustments. The Aqua server can be fine tuned as to the # of workers it deploys which will directly impact memory allocation and scan speed.

**Comment by mitovskaol** [comment]
AQUA has been found ready for the roll out in the production Silver cluster.  The following recommendations for controlling AQUA's resource consumption have been provided by the AQUA vendor team and will be implemented in increments past the roll-out:

1)  Blacklist Sysdig namespaces so that AQUA does not monitor Sysdig containers. 
Sysdig and AQUA co-existence on the same Openshift cluster should not  not a problem.

2)  Set up requests and limits on AQUA enforcers pods. AQUA team to provide the recommendations for those settings.

3) Setup rescanning frequency to **weekly** for now.  Run the rescans at night when the cluster is quiet.

4) Limit what images are scanned, scan only certain environments  - DEV namespaces only in the beginning, openshift and kube namespaces are bypassed by default (we can decide later if these namespaces should be scanned). 

5) Disable the internal AQUA scanning to improve AQUA performance . ENABLE the setting: "Only scan images with scanner-cli daemons.".

**Decision: X Ray will be used to scan images in Artifactory, AQUA will scan images in namespaces -> double security: scanning images at rest and in a runtime environment.**

Next steps:
1) Add HA capabilities to the AQUA Gateway and AQUA Database.
2)  Decide on how the access to AQUA will be opened for product teams (Developer Access to AQUA). Option: AQUA scans all app namespaces, vulnerabilities reports are emailed to the Technical Contacts listed for the namespaces (+ MISO?).
3) Decide on what other features of AQUA will be enabled next.
4) Set up a cron job to prune the AQUA temp directory to control how much space AQUA uses ( @StevenBarre )

**Comment by StevenBarre** [comment]
>1) Blacklist Sysdig namespaces so that AQUA does not monitor Sysdig containers.

I don't think this is needed. I think this was just some consusion around how much resources Sysdig pods are currently using. Scanning shouldn't impact that.

>2) Set up requests and limits on AQUA enforcers pods. AQUA team to provide the recommendations for those settings.

https://docs.aquasec.com/docs/sizing-guide#section-small-50-hosts

We also want to get the namespace changed to conform to the rest of our tools `openshift-bcgov-aqua`.

**Comment by patricksimonian** [comment]
![Screen Shot 2021-03-30 at 11.40.55 AM.png](https://images.zenhubusercontent.com/5c2e50794feb4829c0135179/a02922d3-2aa0-4aeb-a2c0-598c46445f30)

this screen shot is pretty well encapsulates the average utilization of CPU. I ran a scan during this period to see if it would a big difference cpu wise. I did see some spikes in CPU intermittently on longer time frames up to .01 core. 

With respect to scan speeds at our current deployment:

1 gateway
1 webserver
4 enforcers
1 db 

scans are prompt < 1 minute
