### ISSUE TITLE
Artifactory Outage Retro

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#931]
**Describe the issue**
Artifactory was unavailable for about 45 minutes today. This was due to an issue where Artifactory's automated backup scripts were enabled and targeted the default folder, which lives on a PVC that is only 5G. It filled up, preventing Artifactory from recording any logs and things, which crashed Artifactory and prevented it from standing back up again.

**Outcomes**
- [ ] Why were the scripts enabled in the first place? Make sure the backups are not automatically enabled on installation. If they are, let's figure out how to include turning them off as part of the configuration steps.
- [ ] Do we want to perform normal Artifactory backups? Let's see if we can send a backup straight to S3. If so, maybe we should do that. Otherwise, our current backup strat involves backing up the database and reconnecting to the same S3 bucket again.
- [ ] Set up notifications for if/when the Artifactory volumes are getting full so we can act next time before Artifactory goes down.

**Comment by jefkel** [comment]
The volume that filled up has several folders that are of interest both for regular cleanup as well as monitoring in general.  As the service starts to become more heavily used, these directories will begin to see more volume as well.

**/var/opt/jfrog/artifactory/**
`backup/` - used by artifactory built in backups.  Before simply disabling these backups, is there a tested recovery strategy in place?  How often is the recovery strategy validated/tested?
What specific things are being backed up here during an Artifactory backup?
 - configuration settings?
 - postgres data?
 - artifact data?

Are there alternatives available? tested? verified?

`bootstrap/` - only used during boot/setup, can ignore
`data/` - stored data not in cache
 - `./artifactory/` transitional storage before items pushed to object store - This will likely see a lot of use once artifactory hosted repositories are enabled for teams.  Monitoring/Managing the size of this storage location will become critical.
 - other?
 
`etc/` - running configuration (can ignore)
`log/` - logfile storage
 - log rotation should be in place
 - archived log location needs to be managed/pruned
 - current log rotation settings? (looks like the logs have not been rotated since before christmas, is this intended? what is the rotation schedule?)

`work/` - working files - temp job storage (can ignore unless jobs don't clean up after themselves.)

**Comment by caggles** [comment]
> is there a tested recovery strategy in place?

Yes! Recovering by starting up a completely fresh instance of Artifactory over an existing (recovered) Postgres instance with a link to the same S3 instance works just fine. However, we will want to check this again before allowing our users to start using private repos.

> How often is the recovery strategy validated/tested?

For now, the recovery strategy is validated whenever I have time to do so manually. This is definitely something we should automate somehow in the future. 

> What specific things are being backed up here during an Artifactory backup?

The typical Artifactory backup is just a giant dump of everything - configurations, user data, artifacts, everything. It makes it significantly easier to recover than the existing process, but it also takes up a truly enormous amount of space. I have been prodding at Jfrog to see if they can add the ability to stream backups to a volume not mounted to the Artifactory pod. If they can, then it would become considerably easier for us to use this type of backup.

**Comment by jefkel** [comment]
I know that there are currently several UI based configuration changes that occur post install, and it looks like you're adding more configuration changes with this.  Does the current recovery method capture all configuration changes made to the service after install?  (thinking configuration drift since there isn't an automated config push schedule yet).

**Comment by jefkel** [comment]
Change idea:
Currently the volume is mounted as an RWO netapp-block-standard PVC.  This restricts state management/maintenance to the artifactory-ha pod.  All customization for backup changes, archive log cleanup, etc will need to be added to the artifactory base image.

If the volume is changed to an RWX netapp-file-standard PVC, a custom "cleanup" container could be created that runs on a schedule to cleanup old backups (pushing them to object storage first?), delete archived log files to manage log storage, etc.

Before that's changed though, is there a specific reason why BLOCK is being used over FILE?

**Comment by caggles** [comment]
> Does the current recovery method capture all configuration changes made to the service after install? 

No, because the intent is to eliminated all manual configuration changes. When I wrote "let's make sure that this change is part of the configuration steps" I meant adding it to the automated list! We should be able to perform a completely fresh install of Artifactory over an existing Postgres and pointing at an existing S3 bucket and have it all look exactly like it did before.

I like the idea of swapping over to RWX (assuming testing bears out that this is fine!) so we can add a cleanup and notification container!

As for why block is used, this is because file was broken in klab and I felt it was probably better to be consistent between silver and klab rather than use block on klab and file on silver.

**Comment by jefkel** [comment]
Additionally - some of that growth is also found in the member servers as well (specifically, the `data/artifactory/eventual/` folder that is likely to see increased usage with private repos, and the `logs` folder that needs management now.)

thought re: logs/backup folders - if the above (RWX) approach were leveraged, logs could me moved from this PVC as soon as they have been archived (or created - re: backups) to a backup volume, keep a certain # for quick access, and pruned with the knowledge that they will be archived in the backup system for the standard retention period if needed outside of the quick access requirements.
